opentripplanner/otp-ui

- package.json
- packages/core-utils/src/map.js
- packages/core-utils/src/types.js
- packages/endpoints-overlay/package.json
- packages/endpoints-overlay/src/EndpointsOverlay.story.js
- packages/endpoints-overlay/src/endpoint.js
- packages/endpoints-overlay/src/index.js
- packages/endpoints-overlay/src/styled.js
- packages/location-icon/package.json
- packages/location-icon/src/LocationIcon.story.js
- packages/location-icon/src/index.js
- packages/transitive-overlay/package.json
- packages/transitive-overlay/src/TransitiveOverlay.story.js
- packages/transitive-overlay/src/index.js
- packages/transitive-overlay/src/leaflet-canvas-layer.js
- packages/transitive-overlay/src/transitive-styles.js
- yarn.lock
This PR includes both the transitive and endpoints overlays. They are both included because it doesn't make a whole lot of sense to display one without the other.
This PR depends on #17 and #19.
> Transitive and endpoints overlays

- packages/trip-form/package.json
- packages/trip-form/src/DateTimeSelector/index.js
- packages/trip-form/src/DateTimeSelector/styled.js
- packages/trip-form/src/date-time-selector.story.js
This PR adds the date/time selector component that is used to set the trip departure/arrival times.
> Date selector component

- package.json
- packages/geocoder/src/__snapshots__/index.test.js.snap
- packages/geocoder/src/geocoders/abstract-geocoder.js
- packages/geocoder/src/geocoders/arcgis.js
- packages/geocoder/src/geocoders/noapi.js
- packages/geocoder/src/geocoders/pelias.js
- packages/location-field/src/LocationField.story.js
This PR does the following:
- Includes the raw geocoder result in geocode responses (fixes #33)
- Adds a project-wide test script
- Corrects some grammar in a LocationField story
> Raw geocode response

- packages/park-and-ride-overlay/package.json
- packages/vehicle-rental-overlay/package.json
- yarn.lock
> Update packages and yarn.lock so storybook can start

- packages/core-utils/src/map.js
- packages/park-and-ride-overlay/package.json
- packages/transitive-overlay/package.json
- packages/transitive-overlay/src/TransitiveOverlay.story.js
- packages/vehicle-rental-overlay/package.json
- yarn.lock
This fixes the bug described in #36. A story has been added to the transitve-overlay package to demonstrate the fix.
> Get transitive utility to tolerate itineraries without intermediate stops

- packages/core-utils/src/map.js
- packages/itinerary-body/src/__mocks__/itineraries/walk-transit-walk-no-intermediate-stops.json
- packages/transitive-overlay/package.json
- packages/transitive-overlay/src/TransitiveOverlay.story.js
Fixes https://github.com/opentripplanner/otp-ui/issues/47
> Properly render transitive geometry when no intermediate stops exist

- packages/core-utils/src/types.js
- packages/trip-form/src/DropdownSelector/index.js
- packages/trip-form/src/__mocks__/companies.js
- packages/trip-form/src/__mocks__/modes.js
- packages/trip-form/src/util.js
Fixes https://github.com/opentripplanner/otp-ui/issues/46
Also renames "E-Scooter" to "E-scooter" in a few places.
> Fix a few things in the trip form package

- packages/core-utils/src/query.js
Fixes https://github.com/opentripplanner/otp-ui/issues/40
> Add in util function for creating query params for OTP PlannerResource requests

- packages/core-utils/src/__tests__/__snapshots__/query.js.snap
- packages/core-utils/src/__tests__/query.js
- packages/core-utils/src/query.js
Fixes #50 and adds a test to prove fix.
> isNaN bugfix

- packages/trip-details/package.json
- packages/trip-details/src/TripDetails.story.js
- packages/trip-details/src/index.js
- packages/trip-details/src/styled.js
- packages/trip-details/src/trip-detail.js
Refs https://github.com/opentripplanner/otp-ui/issues/38
> Create Trip Details package

- packages/printable-itinerary/package.json
- packages/printable-itinerary/src/ItineraryBody.story.js
- packages/printable-itinerary/src/PrintableItinerary.story.js
- packages/printable-itinerary/src/access-leg.js
- packages/printable-itinerary/src/index.js
- packages/printable-itinerary/src/styled.js
- packages/printable-itinerary/src/tnc-leg.js
- packages/printable-itinerary/src/transit-leg.js
Creates a PrintableItinerary component for displaying printer-friendly itineraries.
Refs https://github.com/opentripplanner/otp-ui/issues/38
> Create printable itinerary package

- packages/base-map/__mocks__/ContextMenuDemo.js
- packages/base-map/src/index.js
- packages/base-map/src/index.story.js
Adds context menu (long-press on mobile devices) support. Addresses #64.
> Basemap right click

- packages/trip-details/src/TripDetails.story.js
This PR corrects the naming of a component in the TripDetails story.
> Fix bad import in TripDetails story.

- packages/trip-form/src/ModeButton/index.js
- packages/trip-form/src/__mocks__/trimet.styled.js
This is a minor PR to allow the title of ModeButton to have a different style when the button is selected, as illustrated in the screenshot below.
> Styling ModeButton title when component is selected

- packages/core-utils/src/index.js
> feat(queryParams): Add queryParams to index.js

- README.md
I was struggling to test a sibling package and this seems like a good way to handle. If someone else has a better way, I'm happy to modify this.
> docs(README): add part about test sibling pkg

- packages/transitive-overlay/package.json
- yarn.lock
Includes two important bug fixes:
- https://github.com/conveyal/transitive.js/pull/50
- https://github.com/conveyal/transitive.js/pull/51
> Update to transitive 0.13.2

- packages/stops-overlay/src/StopsOverlay.story.js
- packages/stops-overlay/src/index.js
> Stop overlay: Remove listener on unmount

- packages/vehicle-rental-overlay/src/index.js
> VehicleRentalOverlay: Make refreshVehicles prop optional.

- packages/park-and-ride-overlay/src/index.js
- packages/stops-overlay/src/stop-marker.js
- packages/vehicle-rental-overlay/src/index.js
> fix: Add back the missing "Plan a trip:" label.

- .releaserc
- .travis.yml
- package.json
- yarn.lock
This PR automates the creation of releases using [semantic-release](https://github.com/semantic-release/semantic-release) and [semantic-release-monorepo](https://github.com/pmowrer/semantic-release-monorepo).
Any pushes to [these branches](https://github.com/semantic-release/semantic-release/blob/master/docs/usage/configuration.md#branches) will trigger a release and publish to GitHub and npm.
> ci(semantic-release-monorepo): 

- packages/core-utils/src/time.js
This adds a temporary fix for a bad timezone import (re #152).
> Temp fix for bad tz import

- packages/core-utils/src/__tests__/__snapshots__/time.js.snap
- packages/core-utils/src/__tests__/time.js
- packages/core-utils/src/time.js
> Resolve bad moment tz import

- jest.config.js
- packages/core-utils/src/__tests__/__snapshots__/query.js.snap
- packages/core-utils/src/__tests__/__snapshots__/time.js.snap
- packages/core-utils/src/__tests__/query.js
- packages/core-utils/src/__tests__/time.js
- packages/core-utils/src/query-params.js
- packages/core-utils/src/query.js
- test-utils/global-setup.js
- test-utils/time.js
Remove config param from getDefaultQuery.
> Remove config param from getDefaultQuery

- packages/transitive-overlay/package.json
- yarn.lock
This PR mirrors https://github.com/opentripplanner/otp-react-redux/pull/176
> fix(deps): Bump transitive-js for label fixes.

- packages/core-utils/src/messages.js
- packages/trip-details/src/TripDetails.story.js
- packages/trip-details/src/index.js
This PR mirrors https://github.com/opentripplanner/otp-react-redux/pull/183
> Allow setting of messages in trip-details

- packages/core-utils/src/__tests__/query.js
- packages/core-utils/src/query.js
- packages/geocoder/src/geocoders/arcgis.js
This PR mirrors the changes from https://github.com/opentripplanner/otp-react-redux/pull/182 for the geocoder and core-utils objects.
> Geocoding fixes

- packages/core-utils/src/__tests__/__snapshots__/query.js.snap
- packages/core-utils/src/__tests__/query.js
- packages/core-utils/src/query-params.js
- packages/core-utils/src/query.js
This PR contains two things:
- a couple of minor tweaks to include some CallTaker related query params
- a fix for #184 
Sorry for bundling these, but they seemed closely related enough to avoid extra PR churn.
> Tweaks for calltaker + Resolution for planParamsToQuery

- packages/endpoints-overlay/package.json
- packages/endpoints-overlay/src/EndpointsOverlay.story.js
- packages/endpoints-overlay/src/index.js
Address comments in https://github.com/opentripplanner/otp-react-redux/pull/165 that request intermediate places be added to the endpoints overlay package.
> Add intermediate places support

- packages/itinerary-body/src/index.js
- packages/location-field/src/index.js
- packages/stops-overlay/src/index.js
- packages/transit-vehicle-overlay/src/index.js
- packages/vehicle-rental-overlay/src/index.js
This PR adds commits for releasing recent merges (namely #200, #192 and the #201 fix).
> Commit for release

- packages/core-utils/package.json
Fix opentripplanner/otp-ui#224.
> Add missing @opentripplanner/geocoder dep

- packages/core-utils/src/route.js
Exports two sorting helpers from the route util file.
> Expose some sorting util functions

- packages/endpoints-overlay/src/endpoint.js
- packages/endpoints-overlay/src/styled.js
> Fix endpoint commands

- packages/trip-form/src/DateTimeSelector/index.js
- packages/trip-form/src/styled.js
This reverts commit d5200496e8ad7675eb14338b8ac8af8a56dd9736.
> fix: revert premature release of trip-form@1.2.0

- __snapshots__/storybook.test.ts.snap
- packages/location-field/src/index.js
- packages/location-field/src/stories/Desktop.story.js
- packages/location-field/src/stories/Mobile.story.js
This PR would allow for a custom component to replace the default Times clear button next to the location-field input.
> feat(loc-field): Allow custom component for clear button

- packages/icons/src/icon-renderer.js
- packages/park-and-ride-overlay/package.json
- packages/park-and-ride-overlay/src/index.js
- packages/stops-overlay/src/default-stop-marker.js
- packages/stops-overlay/src/index.js
- packages/transit-vehicle-overlay/src/components/popups/vehicle-tracker.js
- storybook.test.ts
#277 introduced some regressions and failed to publish some packages. This PR resolves the issues, adds dummy changes to trigger builds of missing package updates, and includes some extra testing to make sure similar regressions don't happen again.
> Resolve Regressions Introduced by #277

- packages/types/package.json
Attempt to push a proper automatic release.
> fix(types): Fix types package description.

- packages/core-utils/src/__tests__/__mocks__/multi-currency-itinerary.json
- packages/core-utils/src/__tests__/__snapshots__/itinerary.js.snap
- packages/core-utils/src/__tests__/itinerary.js
- packages/core-utils/src/itinerary.js
This PR is a subset of #294 that includes `core-utils` changes only.
> Display Multiple Transit Fares if Present - `core-utils` changes only

- packages/core-utils/src/__tests__/__snapshots__/query-params.js.snap
- packages/core-utils/src/query-params.js
- packages/trip-form/src/TripOptions/Checkbox.tsx
- packages/trip-form/src/TripOptions/FeaturedOption.tsx
- packages/trip-form/src/TripOptions/ModeRow.tsx
- packages/trip-form/src/TripOptions/OptionButton.tsx
- packages/trip-form/src/TripOptions/TransitOptions.tsx
- packages/trip-form/src/TripOptions/index.tsx
- packages/trip-form/src/TripOptions/styled.ts
- packages/trip-form/src/settings-selector-panel.story.js
- packages/trip-form/src/test-utils/modes.js
This PR comprises different bug fixes in the new TripOptions component.
> Trip Options Mode Selector Bug Fixes

- packages/trip-details/i18n/en-US.yml
- packages/trip-details/i18n/fr.yml
- packages/trip-details/package.json
- tsconfig.json
This PR cleans up the formatting of i18n messages following a request in https://github.com/opentripplanner/otp-react-redux/pull/508 (e.g. https://github.com/opentripplanner/otp-react-redux/pull/508#pullrequestreview-820355382).
This PR only contains ~a~multiple `chore`/`test` commits for the format changes and will not trigger a package release.
> chore(TripDetails): Tweak i18n message formatting.

- packages/itinerary-body/src/AccessLegBody/index.js
- packages/itinerary-body/src/ItineraryBody/place-row.js
- packages/location-field/package.json
- packages/location-field/src/index.js
- packages/location-field/src/styled.js
- packages/trip-form/src/ModeButton/index.js
- yarn.lock
Accessibility  updates from a 3rd party review of trimet.org.
> Accessibility changes: Adding aria tags to improve screen reader performance

- packages/geocoder/src/apis/here/index.ts
PR just to generate a new release.
> feat(geocoder): Adds HERE Geocoder support.

- packages/core-utils/src/deprecated.js
- packages/core-utils/src/itinerary.js
- packages/core-utils/src/map.js
- packages/core-utils/src/messages.js
- packages/core-utils/src/profile.js
- packages/core-utils/src/query-params.js
- packages/core-utils/src/query.js
- packages/core-utils/src/time.js
- packages/endpoints-overlay/src/endpoint.js
- packages/trip-details/src/index.tsx
- packages/trip-details/src/types.ts
This PR removes use of deprecated methods, or adds notices not to use deprecated methods. 
Blocked by #364
> Remove use of deprecated `core-utils` methods

- packages/itinerary-body/src/AccessLegBody/access-leg-steps.tsx
- packages/itinerary-body/src/AccessLegBody/access-leg-summary.tsx
- packages/itinerary-body/src/AccessLegBody/index.tsx
- packages/itinerary-body/src/AccessLegBody/mapillary-button.tsx
- packages/itinerary-body/src/__mocks__/itineraries/walk-transit-walk-transit-walk-with-accessibility-scores.json
- packages/itinerary-body/src/__mocks__/itineraries/walk-transit-walk-transit-walk.json
- packages/itinerary-body/src/defaults/access-leg-description.tsx
- packages/itinerary-body/src/otp-react-redux/itinerary-body.ts
- packages/itinerary-body/src/otp-react-redux/route-description.tsx
- packages/itinerary-body/src/styled.tsx
Fix #222, fix #394 (see screenshot below).
> Fix ItineraryBody layout

- packages/trip-form/i18n/fr.yml
Adds missing French messages for walk reluctance.
> fix(trip-form/i18n): Add missing French messages

- packages/vehicle-rental-overlay/i18n/en-US.yml
- packages/vehicle-rental-overlay/i18n/fr.yml
- packages/vehicle-rental-overlay/src/index.js
This PR adds i18n support for the vehicle/stations names shown in the popups.
> Add i18n support for default vehicle/station names

- packages/scripts/src/collect-i18n-messages.ts
This PR adds that `fix` commit I forgot in #409!
> fix(packages/scripts): Add fix commit to release changes from #409.

- packages/endpoints-overlay/i18n/en-US.yml
- packages/endpoints-overlay/i18n/fr.yml
- packages/endpoints-overlay/src/endpoint.tsx
Previous code was sending an undefined longitude after dragging an origin/destination marker.
> fix(endpoints-overlay): Fix undefined longitude arg on endpoint drag.

- packages/base-map/package.json
- packages/core-utils/package.json
- packages/endpoints-overlay/package.json
- packages/from-to-location-picker/package.json
- packages/icons/package.json
- packages/itinerary-body/package.json
- packages/location-field/package.json
- packages/location-field/src/types.ts
- packages/park-and-ride-overlay/package.json
- packages/printable-itinerary/package.json
- packages/route-viewer-overlay/package.json
- packages/stop-viewer-overlay/package.json
- packages/stops-overlay/package.json
- packages/transit-vehicle-overlay/package.json
- packages/transitive-overlay/package.json
- packages/trip-details/package.json
- packages/trip-form/package.json
- packages/trip-viewer-overlay/package.json
- packages/vehicle-rental-overlay/package.json
- packages/zoom-based-markers/package.json
This PR updates all internal dependencies. This will result in smaller bundle sizes while also reducing unexpected behavior.
> Update Internal Dependencies 

- packages/base-map/__mocks__/AllVehicles.tsx
- packages/base-map/__mocks__/ContextMenuDemo.tsx
- packages/base-map/src/MarkerWithPopup.tsx
- packages/base-map/src/index.story.tsx
- packages/base-map/src/index.tsx
- packages/base-map/src/styled.ts
- packages/endpoints-overlay/src/endpoint.tsx
- packages/stops-overlay/src/index.tsx
- packages/vehicle-rental-overlay/src/index.tsx
This PR improves the map popup component with shading and rounded border per https://github.com/opentripplanner/otp-react-redux/pull/667#discussion_r1000960712.
> Improve popup style

- packages/itinerary-body/i18n/en-US.yml
- packages/itinerary-body/i18n/fr.yml
- packages/itinerary-body/src/AccessLegBody/rented-vehicle-subheader.tsx
- packages/itinerary-body/src/AccessLegBody/tnc-leg.tsx
- packages/itinerary-body/src/TransitLegBody/alerts-body.tsx
- packages/itinerary-body/src/TransitLegBody/index.tsx
- packages/itinerary-body/src/defaults/access-leg-description.tsx
- packages/itinerary-body/src/defaults/access-leg-step-action.tsx
- packages/itinerary-body/src/defaults/access-leg-step-heading.tsx
- packages/itinerary-body/src/defaults/access-leg-step.tsx
- packages/itinerary-body/src/defaults/compass-direction.tsx
- packages/itinerary-body/src/defaults/line-column-content.tsx
- packages/itinerary-body/src/defaults/route-long-name.tsx
- packages/itinerary-body/src/defaults/stay-on-board.tsx
- packages/itinerary-body/src/defaults/street-name.tsx
- packages/itinerary-body/src/util.ts
This PR attempts to remove some conditional statements from the language files, so that translations are a bit easier (at the expense of some extra code).
> Simplify itinerary translations

- .storybook/preview.js
- .storybook/react-intl.js
- packages/itinerary-body/i18n/en-US.yml
- packages/itinerary-body/i18n/es.yml
- packages/itinerary-body/i18n/fr.yml
- packages/itinerary-body/i18n/ko.yml
- packages/itinerary-body/i18n/vi.yml
- packages/itinerary-body/i18n/zh_Hans.yml
- packages/itinerary-body/src/AccessLegBody/rented-vehicle-subheader.tsx
- packages/itinerary-body/src/defaults/access-leg-description.tsx
This PR fixes some incorrect string handling introduced by #467 (see the rental e-scooter stories in French and Spanish).
The PR also adds entries into the storybook language selector.
> fix(itinerary-body): Fix missing string handling.

- packages/stops-overlay/src/index.tsx
In this PR, event handlers that are set up when mounting the stops overlay are removed when the component unmounts.
> fix(stops-overlay): Remove event handlers on component unmount.

- packages/location-field/package.json
- yarn.lock
> fix(location-field): remove reference to alpha package

- packages/base-map/package.json
- packages/base-map/src/index.tsx
- packages/map-popup/i18n/en-US.yml
- packages/map-popup/i18n/es.yml
- packages/map-popup/i18n/fr.yml
- packages/map-popup/i18n/ko.yml
- packages/map-popup/i18n/vi.yml
- packages/map-popup/i18n/zh_Hans.yml
- packages/map-popup/package.json
- packages/map-popup/src/MapPopup.story.tsx
- packages/map-popup/src/__unpublished__/messages.d.ts
- packages/map-popup/src/index.tsx
- packages/map-popup/src/styled.ts
- packages/map-popup/src/util.ts
- packages/map-popup/tsconfig.json
- yarn.lock
Clone of #472 without the new tile layer itself. This allows #472 to use correct non-alpha package versions.
> OTP2 Tile Overlay Prerequisites 

- packages/trip-details/i18n/en-US.yml
- packages/trip-details/src/index.tsx
- packages/trip-details/src/styled.ts
- packages/trip-details/src/trip-detail.tsx
Adjusts aria roles on the `trip-details` package to be more friendly towards screen readers
> Improve `trip-details` Accessibility

- packages/base-map/package.json
- packages/core-utils/package.json
- packages/endpoints-overlay/package.json
- packages/from-to-location-picker/package.json
- packages/icons/package.json
- packages/itinerary-body/package.json
- packages/location-field/package.json
- packages/map-popup/package.json
- packages/otp2-tile-overlay/package.json
- packages/printable-itinerary/package.json
- packages/route-viewer-overlay/package.json
- packages/stop-viewer-overlay/package.json
- packages/stops-overlay/package.json
- packages/transit-vehicle-overlay/package.json
- packages/transitive-overlay/package.json
- packages/trip-details/package.json
- packages/trip-form/package.json
- packages/trip-viewer-overlay/package.json
- packages/vehicle-rental-overlay/package.json
- packages/zoom-based-markers/package.json
Allows for latest fixes to come into effect.
> Update Internal Dependencies

- packages/location-field/i18n/en-US.yml
- packages/location-field/i18n/es.yml
- packages/location-field/i18n/fr.yml
- packages/location-field/i18n/ko.yml
- packages/location-field/i18n/vi.yml
- packages/location-field/i18n/zh_Hans.yml
- packages/location-field/src/index.tsx
- packages/location-field/src/stories/Desktop.story.tsx
- packages/location-field/src/stories/Mobile.story.tsx
- packages/location-field/src/stories/common.tsx
- packages/location-field/src/styled.tsx
Blocked by/requires #520.
This PR adds a status to the geocoder results, announcing to screen readers the number of results found or any issues with geocoder or location services.
> Location field error a11y

- packages/location-field/i18n/en-US.yml
- packages/location-field/i18n/fr.yml
- packages/location-field/src/index.tsx
- packages/location-field/src/mocks/handlers.js
- packages/location-field/src/options.tsx
- packages/location-field/src/stories/Desktop.story.tsx
- packages/location-field/src/stories/Mobile.story.tsx
- packages/location-field/src/stories/common.tsx
- packages/location-field/src/styled.tsx
This PR adds a spinner visual and status for screen readers to report fetching status (useful for slow geocoders).
> Location field spinner

- packages/base-map/src/index.tsx
- packages/trip-details/package.json
- yarn.lock
The layer selector was previously not accessible by keyboard. This PR rectifies this.
> Keyboard Navigation Support for `base-map` Layer Selector

- packages/itinerary-body/src/__mocks__/itineraries/otp2-with-fareproducts.json
- packages/trip-details/src/fare-table.tsx
- yarn.lock
Co-authored-by: daniel-heppner-ibigroup <Daniel.heppner@ibigroup.com>
Some routes don't have a short name. This PR allows the fare table to handle these routes.
> fix(trip-details): support routes without a short name

- packages/itinerary-body/src/AccessLegBody/mapillary-button.tsx
- packages/itinerary-body/src/otp-react-redux/itinerary-body.ts
- packages/itinerary-body/src/styled.tsx
This PR corrects some clickable region bounds that broke with the recent a11y work. Also correct some general formatting issues.
> fix(itinerary-body): positioning repair post-a11y work

- packages/trip-details/src/fare-table.tsx
Improves accessibility in the fare table
> fix(trip-details): add scope=col to table headers

- packages/base-map/src/index.tsx
> Remove context menu on map pinch

- packages/base-map/package.json
- packages/endpoints-overlay/package.json
- packages/from-to-location-picker/package.json
- packages/icons/package.json
- packages/itinerary-body/package.json
- packages/location-field/package.json
- packages/map-popup/package.json
- packages/otp2-tile-overlay/package.json
- packages/park-and-ride-overlay/package.json
- packages/printable-itinerary/package.json
- packages/route-viewer-overlay/package.json
- packages/stop-viewer-overlay/package.json
- packages/stops-overlay/package.json
- packages/transit-vehicle-overlay/package.json
- packages/transitive-overlay/package.json
- packages/trip-details/package.json
- packages/trip-form/package.json
- packages/trip-viewer-overlay/package.json
- packages/vehicle-rental-overlay/package.json
- packages/zoom-based-markers/package.json
- yarn.lock
Long overdue. It's been since March since we updated internal dependencies. A lot of fixes not fully implemented!
> Update Internal Dependencies (May '23)

- packages/location-field/src/index.tsx
- yarn.lock
Attempt to resolve network-based race conditions. Adds a new abort controller. Aborts and resets on keystroke.
> Location Field: Cancel pending requests on new request

- packages/location-field/src/__tests__/utils.ts
- packages/location-field/src/index.tsx
- packages/location-field/src/options.tsx
- packages/location-field/src/stories/Mobile.story.tsx
- packages/location-field/src/types.ts
- packages/location-field/src/utils.ts
This PR changes the `LocationField` component so that, when typing the name or the address of a provided user-saved location, that location is shown at the top of the suggestions list.
> Suggest saved locations while typing

- packages/trip-form/src/index.ts
Found an export missing from index, this PR is to fix that.
> fix(trip-form): fix a missing export

- packages/stops-overlay/src/index.tsx
Support passing a custom stop color from custom map configuration.
> Support custom stop color

- packages/location-field/package.json
Unpin the geocoder version to prevent duplicates in OTP-RR.
> fix(location-field): Unpin geocoder version.

- packages/trip-details/package.json
- yarn.lock
This implements the changes from #629 in trip details.
> fix(trip-details): update core utils

- packages/otp2-tile-overlay/src/Otp2TileOverlay.story.tsx
Triggers semantic release for https://github.com/opentripplanner/otp-ui/pull/623
> Trigger Semantic release for custom layer colors

- packages/location-field/src/index.tsx
> Fix location field input

- packages/core-utils/src/planQuery.graphql
- packages/trip-form/src/MetroModeSelector/SubSettingsPane.tsx
Also includes master branch repairs
> Metro Mode Selector Spacing Adjustments

- packages/building-blocks/package.json
This PR removes unneeded dependencies to the building-blocks package and will trigger a patch release number for publishing.
> fix(building-blocks): Remove unused dependencies.

- packages/core-utils/src/planQuery.graphql
Unfortunately, some very bad code made it through review
> fix: correctly request agency id

- packages/core-utils/package.json
- packages/itinerary-body/src/ItineraryBody/place-row.tsx
- packages/printable-itinerary/src/accessibility-annotation.tsx
Fixes an issue where if the accessibility score is 0, the badge was not displaying.
> fix(itinerary-body): Show accessibility label if score is 0

- packages/base-map/package.json
- packages/building-blocks/package.json
- packages/core-utils/package.json
- packages/endpoints-overlay/package.json
- packages/from-to-location-picker/package.json
- packages/icons/package.json
- packages/itinerary-body/package.json
- packages/location-field/package.json
- packages/map-popup/package.json
- packages/otp2-tile-overlay/package.json
- packages/park-and-ride-overlay/package.json
- packages/printable-itinerary/package.json
- packages/route-viewer-overlay/package.json
- packages/stop-viewer-overlay/package.json
- packages/stops-overlay/package.json
- packages/transit-vehicle-overlay/package.json
- packages/transitive-overlay/package.json
- packages/trip-details/package.json
- packages/trip-form/package.json
- packages/trip-viewer-overlay/package.json
- packages/vehicle-rental-overlay/package.json
- packages/zoom-based-markers/package.json
- yarn.lock
Updates internal dependencies. This fixes some outdated types versions.
> fix: update internal dependencies

- packages/core-utils/src/planQuery.graphql
- packages/trip-details/src/styled.ts
We had a few flex regressions slip in over the last few months of changes. This PR fixes two of the most egregious. If there's more, feel free to commit to this branch
> Various Flex Regression

- packages/building-blocks/src/index.ts
- packages/building-blocks/src/stories/index.story.tsx
Fixes color export from building blocks as well as incorporates Meta block from Storybook
Credit to @daniel-heppner-ibigroup for this one
> Fix export building blocks

- packages/building-blocks/package.json
- packages/core-utils/package.json
- packages/endpoints-overlay/package.json
- packages/geocoder/src/__snapshots__/index.test.js.snap
- packages/geocoder/src/geocoders/otp.ts
- packages/icons/package.json
- packages/itinerary-body/package.json
- packages/location-field/package.json
- packages/map-popup/package.json
- packages/otp2-tile-overlay/package.json
- packages/printable-itinerary/package.json
- packages/route-viewer-overlay/package.json
- packages/stop-viewer-overlay/package.json
- packages/stops-overlay/package.json
- packages/transit-vehicle-overlay/package.json
- packages/transitive-overlay/package.json
- packages/trip-details/package.json
- packages/trip-form/package.json
- packages/trip-viewer-overlay/package.json
- packages/vehicle-rental-overlay/package.json
- packages/zoom-based-markers/package.json
- yarn.lock
Geocoder v3.0.0 had some rough edges. This cleans all this up and runs prettier on changed code.
Also updates internal dependencies (core utils, geocoder)
> Geocoder breaking change cleanup

- packages/location-field/src/index.tsx
- packages/location-field/src/options.tsx
- packages/location-field/src/stories/Desktop.story.tsx
- packages/location-field/src/types.ts
- yarn.lock
Very basic PR that adds a new prop to hide the new secondary labels we have enabled now.
> fix(location field): support `showSecondaryLabels` prop

- packages/location-field/src/styled.ts
Sorry for tiny tiny PR but this will fix the appearance of the scroll bar on windows! I also tweaked some of the padding within the menu.
> fix(location-field): set overflow to auto

- package.json
- yarn.lock
This adds a command for updating the snapshots since it now requires running an http server
> add command for updating snapshots

- packages/base-map/package.json
- packages/building-blocks/package.json
- packages/core-utils/package.json
- packages/endpoints-overlay/package.json
- packages/from-to-location-picker/package.json
- packages/icons/package.json
- packages/itinerary-body/package.json
- packages/location-field/package.json
- packages/map-popup/package.json
- packages/otp2-tile-overlay/package.json
- packages/park-and-ride-overlay/package.json
- packages/printable-itinerary/package.json
- packages/route-viewer-overlay/package.json
- packages/stop-viewer-overlay/package.json
- packages/stops-overlay/package.json
- packages/transit-vehicle-overlay/package.json
- packages/transitive-overlay/package.json
- packages/trip-details/package.json
- packages/trip-form/package.json
- packages/trip-viewer-overlay/package.json
- packages/vehicle-rental-overlay/package.json
- packages/zoom-based-markers/package.json
- yarn.lock
Mostly to get https://github.com/opentripplanner/otp-ui/pull/768 active in the location field
> Update Internal Dependencies August '24

- packages/core-utils/src/__tests__/itinerary.ts
- packages/core-utils/src/itinerary.ts
isFlex isn't super reliable at the minute. This PR repairs this by increasing the number of conditions we use to accept a leg is flexy
> fix: `isFlex` truthy more of the time

- packages/otp2-tile-overlay/package.json
- packages/stops-overlay/package.json
- packages/vehicle-rental-overlay/package.json
- yarn.lock
eliminate the alpha dependency
> deps: update internal dependencies oct 2 2024

- packages/icons/src/septa-icons.js
Small patch that allows SEptA icons to be more versatile
> fix: allow new METRO pseudo-mode

- packages/location-field/src/index.tsx
My bad, these callbacks are breaking Location Field sorry
> fix(location-field): remove usecallbacks

- packages/core-utils/src/query.js
Using a new field in the geocoderConfig is a bit unclean... Curious if someone has a better idea that doesn't involve drilling.
> Support Alternate Geocoder Methods for Auto-Search

- packages/location-field/src/index.tsx
- packages/location-field/src/stories/__snapshots__/Desktop.story.tsx.snap
- packages/location-field/src/stories/__snapshots__/Mobile.story.tsx.snap
> Disable Spellcheck on Location Field

- packages/transitive-overlay/src/index.tsx
Adds words to a comment so that something can stick to this 'fix' commit so the changes can be pulled down
> fix: expand comment briefly

- packages/itinerary-body/src/ItineraryBody/index.tsx
- packages/itinerary-body/src/ItineraryBody/place-row.tsx
- packages/itinerary-body/src/TransitLegBody/index.tsx
- packages/itinerary-body/src/__mocks__/itineraries/stay-on-board.json
- packages/itinerary-body/src/otp-react-redux/itinerary-body.ts
- packages/itinerary-body/src/otp-react-redux/line-column-content.tsx
- packages/itinerary-body/src/stories/OtpRrItineraryBody.story.tsx
- packages/itinerary-body/src/stories/__snapshots__/OtpRrItineraryBody.story.tsx.snap
- packages/itinerary-body/src/stories/__snapshots__/OtpUiItineraryBody.story.tsx.snap
- packages/itinerary-body/src/styled.tsx
- packages/itinerary-body/src/types.ts
This PR fixes the placement of the stay-on-board dot and improves stay-on-board a11y leg summaries.
> Fix Stay-on-board visual and a11y

- packages/itinerary-body/src/ItineraryBody/place-row.tsx
- packages/itinerary-body/src/stories/__snapshots__/OtpRrItineraryBody.story.tsx.snap
- packages/itinerary-body/src/stories/__snapshots__/OtpUiItineraryBody.story.tsx.snap
Allows implementers the option to highlight interlined legs by adding a class name when legs are interlined
> Highlight Interlines

- packages/building-blocks/src/dropdown/index.tsx
Change role of dropdown to listbox to improve screenreader accessibility
> fix(building-blocks): update dropdown role to listbox

- packages/map-popup/src/MapPopup.story.tsx
- packages/map-popup/src/__snapshots__/MapPopup.story.tsx.snap
- packages/map-popup/src/index.tsx
- packages/map-popup/src/styled.ts
Removes logic to display GTFS stop_id in the map popup package as it is not a public facing value.
> fix(map-popup): remove stop id

- packages/building-blocks/src/dropdown/index.tsx
- packages/building-blocks/src/stories/__snapshots__/dropdown.story.tsx.snap
- packages/trip-form/src/__snapshots__/components.story.tsx.snap
Stop this btn from acting like a submit button when in a form!
> fix(building-blocks): add a role to dropdown button

- packages/location-field/package.json
- packages/location-field/src/index.tsx
- pnpm-lock.yaml
Upgrade to a new and improved debouncer library and restore `useCallback` on the `geocodeAutocomplete` function.
> feat(location-field): upgrade debouncer library

- packages/trip-form/src/MetroModeSelector/utils.ts
- packages/trip-form/src/__tests__/__snapshots__/mode-selector-utils.ts.snap
- packages/trip-form/src/__tests__/mode-selector-utils.ts
- packages/trip-form/src/index.ts
- Adds a util function to determine which mode button and/or mode settings need to be enabled for a given transport mode
- Adds unit tests for the new function
- Converts unit test file to TypeScript and updates snapshot
> Options for transport mode function util function

- packages/map-popup/src/styled.ts
Remove border when no stopId is provided on a stop map-popup
> fix(map-popup): render border only if stopID is provided
