packages/itinerary-body/src/AccessLegBody/index.js
packages/itinerary-body/src/AccessLegBody/leg-diagram-preview.js
packages/itinerary-body/src/ItineraryBody.story.js
packages/itinerary-body/src/TransitLegBody/index.js
packages/itinerary-body/src/index.js
packages/itinerary-body/src/place-row.js
packages/itinerary-body/src/styled.js

This PR adds a slot to the ItineraryBody component for a custom component that can render the route description. See a new story titled `ItineraryBody with E-scooter rental + transit itinerary with OTP-RR styling and customizations` for an example implementation.
Refs #18.

Add slot for custom route description component

---

packages/endpoints-overlay/src/EndpointsOverlay.story.js
packages/endpoints-overlay/src/endpoint.js
packages/endpoints-overlay/src/index.js

Fixes #37. Allows passing a component as a prop to the endpoints overlay which is then used to render the map icons for the endpoints.

Allow creation of custom endpoint icons

---

packages/from-to-location-picker/package.json
packages/trip-form/package.json

The 'module' (set to src/index.js) in project.json is problematic.  Removing a couple of instances.  Fixes #54

fix(package.json): fixes #54 -- remove 'module' from project.json

---

packages/core-utils/src/types.js
packages/stop-viewer-overlay/src/StopViewerOverlay.story.js
packages/stop-viewer-overlay/src/default-stop-marker.js
packages/stop-viewer-overlay/src/index.js
packages/stops-overlay/package.json
packages/stops-overlay/src/StopsOverlay.story.js
packages/stops-overlay/src/index.js
packages/stops-overlay/src/stop-marker.js

This PR adds a slot to the StopOverlay component to allow for the full customization of marker that is used to render stops on the map. The story has been modified to show how to use the default marker if desired.
Fixes #62 
This PR is built on top of #72.

Stop layer marker customization

---

packages/core-utils/src/types.js
packages/stops-overlay/package.json
packages/stops-overlay/src/StopsOverlay.story.js
packages/stops-overlay/src/index.js
packages/stops-overlay/src/stop-marker.js

This PR adds a slot to the StopsOverlay component to allow for the full customization of markers that are used to render stops on the map. The story has been modified to show how to use the default marker if desired.
Fixes #59

Allow full customization of stop markers

---

packages/core-utils/src/map.js
packages/transitive-overlay/package.json
packages/transitive-overlay/src/transitive-styles.js

This PR has a slight improvement to the display of car legs that are followed or preceded by walking legs. Before, no transitive place was shown at these transitions and the line would sort of just change from grey to blue or vice versa. Now, a node is drawn and a label is drawn. This affects P&R and TNC requests.
**Before:**
**After:**

Transitive improvements

---

packages/endpoints-overlay/src/endpoint.js
packages/endpoints-overlay/src/index.js

This overlay doesn't need the from or to locations to be defined in order to work properly. This PR updates the prop types to match that expectation.

endpoints-overlay: make from/to locations optional props

---

packages/trip-form/src/ModeIcon/index.js
packages/trip-form/src/SettingsSelectorPanel/index.js
packages/trip-form/src/__mocks__/custom-icons.js
packages/trip-form/src/components.story.js
packages/trip-form/src/settings-selector-panel.story.js
packages/trip-form/src/util.js

This PR addresses #87 by allowing implements to pass custom icons into `SettingsSelectorPanel` the way OTP-react-redux does, so implementers can optionally use icons in the mode selection pane other than the ones from the OTP-UI icons package. In particular, in OTP-UI icons, the "Take Transit" icon is the TriMet's logo, so with this PR, implementers will be able to change it.
This PR also fixes improper knob types used in some storybook stories.

Trip form custom icons

---

packages/base-map/src/index.js
packages/endpoints-overlay/src/endpoint.js
packages/from-to-location-picker/src/index.js
packages/from-to-location-picker/src/index.story.js
packages/location-field/src/index.js
packages/stops-overlay/src/index.js

To be consistent with the `location-field` and the `stops-overlay` packages, this changes the `setLocation` callback in the `from-to-location-picker`and `endpoints-overlay` packages to have the same data structure.

Make from-to-location-picker and endpoints-overlay return consistent data structures and one other thing

---

packages/stop-viewer-overlay/src/StopViewerOverlay.story.js
packages/stop-viewer-overlay/src/default-stop-marker.js
packages/stop-viewer-overlay/src/index.js

This PR renames all occurrences of `stopData` to `stop` to have consistency with other packages. Fixes #93.

Stop viewer overlay rename stopdata

---

packages/trip-form/src/DateTimeSelector/index.js

This quick PR adds documentation about the rendering modes (modern browsers vs. legacy browsers) and related props for the DateTimeComponent, as requested by [this OTP-RR PR comment](https://github.com/opentripplanner/otp-react-redux/pull/139#discussion_r398585358).

Document the rendering modes for DateTimeSelector

---

packages/trip-details/src/trip-detail.js

This PR makes a slight adjustment to expand/collapse icons of the trip detail calories description (see screenshot).

fix(trip-detail): Make expand/collapse icon size slightly smaller

---

packages/itinerary-body/src/index.js

The `toRouteAbbreviation` property isn't needed in some implementations that use a custom `LineColumnContent` component. Therefore, this PR makes it optional.

Make the toRouteAbbreviation property optional

---

packages/core-utils/src/itinerary.js

When creating the core-utils package, the dependent turf packages were updated to the latest version. As a part of this, one of the arguments for a call to turf-along is now incorrect. This PR fixes it so that the argument is called with the correct format.

Update call to turf-along to use updated argument format

---

.travis.yml

This PR adds a `.travis.yml` file to the repo root directory so that the Travis CI system can automatically execute tests each time someone pushes new commits to a pull request on GitHub.
Prerequisite: This repo needs to be linked on Travis CI.

Add Travis to run tests

---

.travis.yml
packages/core-utils/src/__tests__/__mocks__/itinerary.json
packages/core-utils/src/__tests__/__snapshots__/itinerary.js.snap
packages/core-utils/src/__tests__/itinerary.js
packages/core-utils/src/itinerary.js

This PR replaces the `routeComparator` sorting function in `core-utils/itinerary` with the improved version from OTP-react-redux. OTP-react-redux will in turn rely on this incoming version of the route sorting function.
EDIT: To run the route sorting tests (and all the tests in other packages in this repo) on your computer, use `yarn unit`.

Port improved route sorting from OTP-react-redux

---

packages/location-field/src/LocationField.story.js
packages/location-field/src/index.js

This PR fixes #133. To use, set the `autoFocus` prop of the control that has the initial focus to `true` as you would do with other HTML input controls.

LocationField: Add autoFocus prop.

---

packages/core-utils/src/query.js

Removes config arg from these method calls and from `planParamsToQuery`.

Invoke getCurrentTime/getCurrentDate correctly

---

packages/itinerary-body/src/otp-react-redux/itinerary-body.js

This mirrors
https://github.com/opentripplanner/otp-react-redux/pull/184/commits/ed5fb366e495f8bd55a792b5c69582c9ec461fc3

fix(itinerary-body (otp-rr)): Fix route label padding for transit legs

---

packages/icons/src/companies/index.js

This change provides a helpful warning message in the event that a company icon is not found.

Provide a helpful warning for missing company icon

---

packages/core-utils/src/__tests__/__snapshots__/query.js.snap
packages/core-utils/src/__tests__/query.js
packages/core-utils/src/query.js

If there is no value defined for a fromPlace/toPlace the `parseLocationString` call fails. This fixes that issue.

Fix undefined error on value.split call

---

packages/location-icon/src/LocationIcon.story.js
packages/location-icon/src/index.js
packages/location-icon/src/styled.js

This PR relaxes proptypes for LocationIcon. If `from` or `to` is not used for `locationType`, a generic Circle icon will be rendered. This will allow for an icon to be used with IntermediatePlaces in the Call Taker module.

Relax proptypes for LocationIcon

---

packages/trip-form/src/__mocks__/companies.js
packages/trip-form/src/util.js

This PR fixes #196 by adding a missing null check before rendering rental vehicle company icons.
To test in Storybook:
1. Click the first story for `SettingsSelectorPanel`
2. Click "Transit+Biketown"
3. There should not be an error message filling the canvas.
~To test in OTP-RR locally:~
- ~In OTP-RR's `package.json`, replace the version of `@opentripplanner/trip-form` with the path to local version.~
- ~Try adding a rental company to OTP-RR's config as suggested in #196.~
- ~launch OTP-RR, click Travel Preferences > Bikeshare.~
~The MOD UI screen should not go blank.~

Add missing null check before rendering company icon.

---

packages/itinerary-body/src/ItineraryBody.story.js
packages/itinerary-body/src/defaults/time-column-content.js
packages/itinerary-body/src/demos/index.js
packages/itinerary-body/src/index.js
packages/itinerary-body/src/place-row.js

This PR fixes #191 and introduces a slot for custom rendering of the contents in the time column of the itinerary component.

Itinerary Body: TimeColumnContent slot

---

packages/icons/src/standard-mode-icon.js

The StandardRail icon wasn't used in the StandardModeIcon for the `rail` mode. This PR fixes that.

Use the StandardRail icon for the rail mode

---

packages/base-map/package.json
packages/endpoints-overlay/package.json
packages/from-to-location-picker/package.json
packages/icons/package.json
packages/itinerary-body/package.json
packages/location-field/package.json
packages/park-and-ride-overlay/package.json
packages/printable-itinerary/package.json
packages/route-viewer-overlay/package.json
packages/stop-viewer-overlay/package.json
packages/stops-overlay/package.json
packages/transit-vehicle-overlay/package.json
packages/transitive-overlay/package.json
packages/trip-details/package.json
packages/trip-form/package.json
packages/trip-viewer-overlay/package.json
packages/vehicle-rental-overlay/package.json
packages/zoom-based-markers/package.json
yarn.lock

This PR fixes #201. It made sense to bump core-utils in all other packages at the same time.

build(deps): Bump core-utils to 2.1.0

---

packages/location-field/src/index.js
packages/location-field/src/styled.js

This PR fixes #199 and adds `aria-label` props for the drop-down and buttons contained in the `LocationField` component.
To test: open the stories in Storybook for `LocationField`, click on the accessibility tab below the canvas. Accessibility warnings regarding the **buttons** and **input** controls for `LocationField` should no longer appear. (Other accessibility issues listed for `LocationField` are outside of the scope of #199 and this PR.)

improvement(a11y): Add a11y props for LocationField.

---

packages/itinerary-body/package.json
packages/itinerary-body/src/AccessLegBody/tnc-leg.js
packages/itinerary-body/src/ItineraryBody.story.js
packages/itinerary-body/src/TransitLegBody/index.js
packages/itinerary-body/src/TransitLegBody/view-trip-button.js
packages/itinerary-body/src/__mocks__/itineraries/fare-components.json
packages/itinerary-body/src/defaults/transit-leg-summary.js
packages/itinerary-body/src/index.js
packages/itinerary-body/src/otp-react-redux/itinerary-body.js
packages/itinerary-body/src/otp-react-redux/route-description.js
packages/itinerary-body/src/otp-react-redux/view-stop-button.js
packages/itinerary-body/src/place-row.js
packages/itinerary-body/src/styled.js
yarn.lock

This PR:
- adds fare information for individual legs (which is derived from the fare details part of the fare object). The fare for a transit leg is displayed only when the stops list is expanded (see screenshot).
- fixes a bunch of issues with styled components (that were addressed following this comment about font sizes -> https://github.com/opentripplanner/otp-ui/pull/209#discussion_r474744850)
- renames the otp-rr itin body stories to be more concise.

Add fare information to transit leg

---

packages/core-utils/src/__tests__/__snapshots__/query.js.snap
packages/core-utils/src/__tests__/query.js
packages/core-utils/src/query-params.js
packages/core-utils/src/query.js

Fixes https://github.com/opentripplanner/otp-ui/issues/203.
I marked this PR as a fix, because it's unlikely that anybody ever used this before since it couldn't have worked very well. This PR changes the assumption about how query parameters for the `intermediatePlaces` are generated in that they are not expected to be parsed from (or stringified into) a comma-separated string, but instead should be parsed from (or stringified into) an array of strings. The `query.getRoutingParams` and `query.planParamsToQuery` are both assumed to use the [qs](https://www.npmjs.com/package/qs) package to do the parsing (and stringifying) from (and to) raw URL query params. This package has a way of parsing (and stringifying into) query params that have multiple of the same parameter which is the format …

Properly parse and stringify intermediate places

---

packages/location-field/src/LocationField.story.js
packages/location-field/src/index.js

This PR fixes #183 by correctly handling when there are no features returned from a geocode response. It also adds a message if there is an error communicating with the geocoder or if no results are found, which I think is useful behavior (otherwise there is no indication that a search completed). Curious to have @fpurcell's thoughts on that behavior though.
A new story with a bad API key configured for geocode.earth is at http://localhost:5555/?path=/story/locationfield--locationfield-with-bad-api-key-handles-bad-autocomplete

Handle error response from geocoder

---

packages/itinerary-body/src/__mocks__/config.json
packages/itinerary-body/src/place-row.js
yarn.lock

Changes were added in #189 that resulted in a new v3 release of core-utils and some releases on other packages. One of those packages was the itinerary-body package, but it hadn't yet been updated to have an official dependency on core-utils v3. Therefore, this introduced code in the 1.x.x pipeline of the itinerary-body package that is now a bug. This PR reverts changes that assumed core-utils v3 within the itinerary-body package to maintain consistency with coreUtils 2.x and the previous way of defining transitOperators in the config. This PR will create a patch release of the itinerary-body package.
Another PR will change this code back again to the v3 style transit operators config and will contain a commit with a breaking change that will make sure the itinerary-body package gets a …

Revert to old transitOperator lookup

---

packages/base-map/package.json
packages/from-to-location-picker/package.json
packages/icons/package.json
packages/location-field/package.json

This is part 1 of 3 to update internal packages to use core-utils v3. This PR only updates the packages that have no dependencies on otp-ui packages that have a dependency on core-utils. If we were to include packages such as vehicle-rental-overlay in this PR, it would not be sufficient to ensure that all other packages that the vehicle-rental-overlay package depends on also have a dependency on core-utils v3. So, future PRs will bump core-utils and other relevant packages with a core-utils dependency until every package that has some kind of dependency on core-utils has been released. In doing so, there will be only one release per package which will look much cleaner than multiple releases that update a single package at a time. Hope I explained this well and this is ok.

Update opentripplanner dependencies to latest versions (core-utils v3 update part 1)

---

packages/endpoints-overlay/package.json
packages/itinerary-body/package.json
packages/itinerary-body/src/__mocks__/config.json
packages/itinerary-body/src/place-row.js
packages/park-and-ride-overlay/package.json
packages/printable-itinerary/package.json
packages/route-viewer-overlay/package.json
packages/stop-viewer-overlay/package.json
packages/trip-form/package.json
packages/trip-viewer-overlay/package.json
packages/zoom-based-markers/package.json
yarn.lock

This is part 2 of 3 to update internal packages to use core-utils v3. This updates all packages that have indirect dependencies on core-utils via other packages. The zoom-based-markers package is still depended on by other packages, so those packages will be included in part 3.
This PR also includes a breaking change commit to the itinerary-body package to reflect the requirement for changing the config of the transit operators to include the feed and agency IDs.

Update opentripplanner dependencies to latest versions (core-utils v3 update part 2)

---

packages/core-utils/src/route.js

This change makes it possible to sort routes based off of agency info from OTP alone even when a zero-length array is sent as the transit operators. otp-react-redux initializes the transitOperators value to an empty array if it is not included in the config.

Better sort routes with zero length transit operators config

---

packages/itinerary-body/src/place-row.js
packages/itinerary-body/src/styled.js

This PR is intended to supercede #235. It provides the following tweaks:
- moves the title prop from MapIcon to MapButton (so that a hover anywhere on the button will show the alt text)
- adds a messages prop with default values (to support future/planned internationalization).

Tweak map icon message

---

packages/core-utils/src/__tests__/__mocks__/config.json
packages/core-utils/src/__tests__/__snapshots__/query.js.snap
packages/core-utils/src/__tests__/query.js
packages/core-utils/src/query.js

This PR closes #243 by modifying `getDefaultQuery` and `isNotDefaultQuery` to handle overriding default query params with values from `config#defaultQueryParams`.

feat(query.js): override query params w/ config#defaultQueryParams

---

packages/transitive-overlay/package.json
yarn.lock

This PR adds the latest visual changes to transitive.js 0.13.7.

Upgrade transitive-js to 0.13.7.

---

packages/vehicle-rental-overlay/src/DefaultMarkers/index.js

This prevents a white-screen-of-death error when a bike rental station has 0 bikes available and 0 spaces available.

Hide zero-capacity bike rental stations

---

packages/core-utils/src/map.js

This PR enables passing a custom route labeling function as suggested in https://github.com/opentripplanner/otp-ui/pull/246#discussion_r630499498 when converting OTP itineraries to transitive.js itineraries.

Custom route labels in transitive itineraries

---

packages/transitive-overlay/package.json
packages/transitive-overlay/src/TransitiveOverlay.story.js
packages/transitive-overlay/src/index.js

For some reason I was convinced the transitive options were directly exposed but I was wrong... so we have to expose the new styles and labeledModes on the components.
EDIT: In response to https://github.com/opentripplanner/otp-ui/pull/246#discussion_r630499498, this PR now requires #248. To test, merge the changes from #248 into this branch and run `yarn dev`.

fix(TransitiveOverlay): Expose styles and labeledModes transitive props.

---

packages/itinerary-body/src/demos/index.js

This PR fixes #241. There's not actually an issue with the otp-ui library code, rather a missing prop on the storybook example that uses `CustomTransitLegSummary`.

Add required onClick prop to CustomTransitLegSummary

---

packages/core-utils/src/types.js

There is at least one type of step for which the OTP engine doesn't return the absoluteDirection attribute for a step: riding an elevator. This change prevents a prop type error from being raised for those types of steps.  See the payload of an elevator step below:
I looked over the code base to see if making this prop optional had any other implications and it doesn't seem to, its only used when the step is a `DEPART` type and the `ELEVATOR` type has its own handling in the only [section](https://github.com/opentripplanner/otp-ui/blob/master/packages/core-utils/src/itinerary.js#L132) that its referenced

Make absoluteDirection prop optional on stepsType

---

packages/core-utils/README.md

#259 didn't end up triggering a release in core-utils, so this PR has the proper commit that will do that.
Fixes https://github.com/opentripplanner/otp-ui/issues/260

Include brief documentation update to trigger release

---

packages/vehicle-rental-overlay/package.json
packages/vehicle-rental-overlay/src/index.js

Closes opentripplanner/otp-react-redux#414
The issue was the `VehicleRentalOverlay` component taking a `visible` prop, but doing nothing with it...

Hide Vehicle Overlay When Appropriate 

---

packages/itinerary-body/README.md
packages/itinerary-body/src/TransitLegBody/alerts-body.js
packages/itinerary-body/src/TransitLegBody/index.js
packages/itinerary-body/src/index.js
packages/itinerary-body/src/place-row.js
packages/itinerary-body/src/stories/OtpUiItineraryBody.story.js
packages/itinerary-body/src/stories/itinerary-body-defaults-wrapper.js
packages/itinerary-body/src/styled.js

New story: http://localhost:5555/?path=/story/itinerarybody-otp-ui--custom-alert-icons-itinerary
* Add props to the itinerary body component for the two alert icons and
pass them down through the itinerary tree to the appropriate child
components
* Reconfigure the existing icon components to be overrideable prop
defaults
* Add a story to the itinerary storybook to illustrate this new
functionality

Make alert icons on itinerary configurable

---

packages/vehicle-rental-overlay/src/VehicleRentalOverlay.story.js
packages/vehicle-rental-overlay/src/index.js
packages/vehicle-rental-overlay/src/leaflet-layer-control-interface.tsx

Also fix the vehicle rental storybook stories and improve the storybook example to show detailed controlling of the vehicle rental layer via handlers of layer control events.

Properly render vehicle rental layer with 0 stations

---

__snapshots__/storybook.test.ts.snap
packages/trip-details/src/styled.js
packages/trip-details/src/trip-detail.js

The a11y fixes branch (https://github.com/opentripplanner/otp-ui/pull/283) didn't apply aria labels correctly. This PR corrects that.

fix(trip-details): correctly apply aria labels

---

packages/core-utils/src/__tests__/itinerary.js
packages/core-utils/src/itinerary.js

Proposing to expose the currency code of OTP itineraries through method `calculateFares`, so that implementers don't have to re-write that function's code to figure out the currency used. The intended use is to remove the `currency` prop introduced in #281 from the `TripDetails` component.

Make calculateFares also return currency code

---

packages/geocoder/package.json
packages/geocoder/src/geocoders/abstract-geocoder.js
packages/geocoder/src/geocoders/arcgis.js
packages/geocoder/src/geocoders/noapi.js
packages/location-field/src/index.js
packages/location-field/src/styled.js
yarn.lock

#283 changed the role of the menu items in the location field dropdown. This prevented the onFocus handler from ensuring their click handler fires before the dropdown disappears, resulting in menu items not being clickable.
This PR also updates the geocoder to work in more build environments, updating to use the latest lonlat.
Also includes a few related patches for location-field to make integration into otp-rr easier.

Fix regressions introduced in previous releases

---

packages/location-field/src/index.js
packages/location-field/src/utils.js

In the last update, only the such results showed the enhanced location information (street, zip code/neighborhood). With this update, that information is displayed in the main location field as well as recent results history.

fix(packages/location-field): generate better labels for all fields where locations are shown

---

packages/types/package.json

Attempt to allow TypeScript types to be found during OTP-UI CI builds.

fix(types): Remove module entry in types/package.json

---

packages/core-utils/src/map.js

Avoids drawing straight lines through roads and houses when `interStopGeometry` is missing by using `legGeometry`, if present. This does bring the caveat of some transitive features no longer being supported when the `interStopGeometry` is missing.
Closes https://github.com/opentripplanner/otp-react-redux/issues/489

fix(core-utils/map): use legGeometry instead of drawing straight lines

---

.github/workflows/node-ci.yml

As per https://github.com/semantic-release/github/issues/175#issuecomment-877059469, this PR prevents persisting credentials used during checkout which will hopefully fix the semantic release bot.

Hopefully Fix Package Releases

---

packages/location-field/src/index.js
packages/location-field/src/mocks/autocomplete.json

This PR adds a new sort within `locationField` which sorts results by distance, if provided. Results with distance are always prioritized.

feat(location-field): sort results by distance if provided

---

packages/park-and-ride-overlay/src/index.js
packages/transit-vehicle-overlay/src/components/markers/RotatedMarker/index.js
packages/vehicle-rental-overlay/src/DefaultMarkers/index.js

Add an optional Marker prop called 'keyboard' (defaulted to a value of 'false'), which is used by leaflet to either set tabindex="0" (when true) or nothing in the resulting div.  This is important for keyboard-only and SR users, since the current map has potentially 10s to 100s of markers, each that are in the tab order -- the result is that one gets stuck in tab hell on the map, without an exit.  The keyboard=false value will now allow tabbing thru the app, with any variety of marker layer active (stop, vehicle, P&R, bike/scooter share, etc...), and no black hole where the tab order gets stuck w/out an exit.

ACCESSIBILITY: leaflet marker prop to control tabindex 

---

.gitignore
packages/trip-details/src/index.tsx
packages/trip-details/tsconfig.json

The introduction of the types package seems to have had some side-effects that prevents `yarn install` from working properly. This PR attempts to address these issues.

Post-types package fixes

---

packages/trip-form/src/TripOptions/FeaturedOption.tsx
packages/trip-form/src/TripOptions/OptionButton.tsx
packages/trip-form/src/TripOptions/styled.ts

- Add ariaLabel and ariaChecked to TripOptions/OptionButton(s).
- Adds aria label to the (?) image for shared modes, to describe via screen reader what those buttons opened up.
- git ignore / cleanup

Accessibility trip form buttons

---

packages/location-field/src/index.js
packages/location-field/src/mocks/autocomplete.json
packages/location-field/src/stories/Desktop.story.js

This PR adds a prop to the location field that allows certain layers to avoid the distance based sorting all results are otherwise subjected to.

feat(location-field): allow special layers to avoid distance sorting

---

packages/location-field/src/index.js

#316 changed the aria role for the list items, which broke the `onFocus` handler. This prevented items from being clicked. 
This PR adjusts the `onFocus` handler to use the updated aria role, restoring correct behavior.

fix(location-field): update onFocus handler to use updated aria roles

---

packages/core-utils/src/map.js

This is a small change to not use the OTP-generated shapes. These could often be inaccurate. 
The route viewer is not affected by these changes, as the route viewer does not render flex legs via transitive.

Render Flex Legs as arcs in Itinerary View

---

packages/core-utils/src/__tests__/__snapshots__/query-params.js.snap
packages/core-utils/src/__tests__/__snapshots__/query.js.snap
packages/core-utils/src/__tests__/query-params.js
packages/core-utils/src/__tests__/query.js
packages/core-utils/src/query.js

Part of https://github.com/opentripplanner/otp-react-redux/pull/530
Small adjustment to how we replace `FLEX` with the 3 OTP flex modes. The new approach is more computationally expensive, but more resilient in more situations.

fix(core-utils): more resiliently expand flex mode

---

packages/trip-form/src/SettingsSelectorPanel/query-params-i18n.tsx

This PR fixes #339 by using a more precise `METERS_PER_MILE` value and some rounding logic.

Fix rounding so that default selector values work

---

packages/transitive-overlay/src/leaflet-canvas-layer.js

Transitive overlay was relying on the Leaflet map object being available pretty quickly. In some environments it takes some time to arrive, so this PR resolves the issue by skipping draw when the map object isn't available.

fix(transitive-overlay): avoid crash on slow leaflet load

---

packages/humanize-distance/package.json
packages/humanize-distance/src/index.ts

~Requires #355 (for an updated correct dependency version).~ Update: #355 is now merged in master.
This PR adds i18n support to the `humanize-distance` package while maintaining backwards compatibility (use of `react-intl` remains optional with this package).

Humanize distance intl

---

packages/route-viewer-overlay/src/index.js

This PR resolves crashes found in OTP-RR. We were checking for lack of geometry, but not empty geometry.

fix(route-viewer-overlay): avoid crash on empty but not missing geometry

---

packages/geocoder/src/apis/here/index.ts
packages/geocoder/src/geocoders/types.ts
packages/geocoder/src/index.story.tsx

This is a one line fix for the Geocoder package, which was sometimes failing to correctly generate correct results using HERE when a boundary was provided along with focusPoint. Most of the changes in this PR was enhancements for the story to make testing easier.

fix(geocoder): fix chainquery bug with HERE boundary filter

---

packages/core-utils/src/deprecated.js
packages/core-utils/src/itinerary.js
packages/core-utils/src/map.js
packages/core-utils/src/messages.js
packages/core-utils/src/profile.js
packages/core-utils/src/query-params.js
packages/core-utils/src/query.js
packages/core-utils/src/time.js

No breaking changes at this point. All depurated functions are still present, just moved outside of where they used to be. Backwards compatibility was the focus, although some parameters that were not used have been removed.

Remove all English strings from core-utils

---

packages/core-utils/src/__tests__/__snapshots__/query-params.js.snap
packages/core-utils/src/query-params.js
packages/core-utils/src/query.js

A stub was present, but this PR adds a full entry for it. A new `otp2` field in the query object is used to switch between walk reluctance and the max walk distance, which is no longer supported by OTP2.

Add walk reluctance to `core-utils`

---

packages/route-viewer-overlay/src/index.js

This PR adds a very minor adjustment to the route viewer overlay making it less mysterious when the bounds are updated.

Route Viewer Overlay bounds update callback

---

packages/from-to-location-picker/i18n/en-US.yml
packages/from-to-location-picker/i18n/fr.yml
packages/from-to-location-picker/src/index.story.tsx
packages/from-to-location-picker/src/index.tsx
packages/from-to-location-picker/src/types.ts

This PR adds a `label` prop to the `FromToLocationPicker` component. If `label` is set to `true`, a default i18n-able label text is shown, that will simplify reusing message strings code in other packages in this repo and others that implement this component.

feat(FromToLocationPicker): Add label prop.

---

packages/core-utils/src/__tests__/__snapshots__/query-params.js.snap
packages/core-utils/src/query-params.js

This PR adds some more OTP2 support to `core-utils`. Most notably this fixes [#594](https://github.com/opentripplanner/otp-react-redux/issues/594) and provides support for #371

fix(core-utils): improve OTP2 support

---

packages/vehicle-rental-overlay/src/index.js

Fix #376 again, this time on first render when the user initially clicks the layer (copy `lib` or `esm` to OTP-RR to see that in action).

fix(VehicleRentalOverlay): Ensure rendering when displaying for first time

---

.storybook/react-intl.js
packages/stops-overlay/i18n/en-US.yml
packages/stops-overlay/i18n/fr.yml
packages/stops-overlay/package.json
packages/stops-overlay/src/StopsOverlay.story.js
packages/stops-overlay/src/default-stop-marker.js

This PR adds i18n support to the Stops Overlay component (does not include TypeScript because of MapLayer typing issues).

Stops overlay i18n

---

packages/park-and-ride-overlay/package.json
packages/park-and-ride-overlay/src/index.js

This PR makes the P/R overlay to use i18n from `from-to-location-picker` 2.1.0.
Typescript is not included in this PR because of issues with react-leaflet's `MapLayer` class.
A new "fix" release will be created when merging this PR.

fix(ParkAndRideOverlay): Use i18n from FromToLocationPicker 2.1.0.

---

packages/core-utils/package.json
packages/itinerary-body/package.json
packages/itinerary-body/src/demos/index.tsx
packages/printable-itinerary/package.json
packages/trip-form/package.json
yarn.lock

Some package updates aren't working in otp-rr due to missing internal dependency updates. This PR resolves that.

update internal dependency versions

---

packages/from-to-location-picker/package.json
packages/from-to-location-picker/src/types.ts

As mentioned in https://github.com/opentripplanner/otp-ui/pull/367, `from-to-picker` changes had to be extracted to allow unit tests to pass

Add Typescript to `core-utils` - `from-to-picker` updates 

---

packages/core-utils/src/deprecated.js
packages/core-utils/src/itinerary.js
packages/itinerary-body/src/AccessLegBody/index.tsx
packages/itinerary-body/src/AccessLegBody/tnc-leg.tsx
packages/itinerary-body/src/ItineraryBody/index.tsx
packages/itinerary-body/src/ItineraryBody/place-row.tsx
packages/itinerary-body/src/demos/index.tsx
packages/itinerary-body/src/types.ts
packages/types/src/index.ts

No breaking changes in this PR that just removes superficial uses of `TimeOptions` and related code in the `itinerary-body` demo code.

Deprecate TimeOptions

---

packages/trip-details/package.json
packages/trip-details/tsconfig.json
yarn.lock

Dev-time references to other packages in the same mono repo are not necessary. This fixes the build that's reported broken after merging #403 (it probably became broken after merging #367).

chore(trip-details:deps): Remove types pkg dep

---

package.json
packages/scripts/package.json
packages/scripts/src/collect-i18n-messages.ts
packages/scripts/src/index.ts
packages/scripts/src/run-collect-i18n-messages.ts
packages/scripts/src/run-validate-i18n.ts
packages/scripts/src/validate-i18n.ts

This PR is an attempt to fix the semantic release failure from merging #287 by adding the missing index file to the `scripts` package (that requires separating code that runs right away from the reusable code).

Fix scripts package

---

packages/trip-form/src/DateTimeSelector/index.tsx
packages/trip-form/src/components.story.tsx

This PR adds a `timeZone` prop to the `DateTimeSelector` component, so that when the user clicks "Leave now", the current time passed to the OTP query parameters is the local time at the specified timeZone (which is not necessarily the user time zone). This is useful when querying OTP for agencies in a different time zone than the user time zone.

fix(DateTimeSelector): Add and use timeZone prop to format current time

---

packages/location-field/src/utils.ts

The zip codes were distracting more than they were helping, so this PR removes them.

fix(location-field): remove zip code from previews

---

packages/base-map/src/index.story.tsx
packages/base-map/src/index.tsx
packages/base-map/src/styled.ts
packages/endpoints-overlay/package.json
packages/endpoints-overlay/src/EndpointsOverlay.story.tsx
packages/park-and-ride-overlay/package.json
packages/park-and-ride-overlay/src/ParkAndRideOverlay.story.js
packages/route-viewer-overlay/package.json
packages/route-viewer-overlay/src/RouteViewerOverlay.story.js
packages/stop-viewer-overlay/package.json
packages/stop-viewer-overlay/src/StopViewerOverlay.story.tsx
packages/stops-overlay/package.json
packages/stops-overlay/src/StopsOverlay.story.tsx
packages/transit-vehicle-overlay/package.json
packages/transit-vehicle-overlay/src/index.story.tsx
packages/transitive-overlay/package.json
packages/transitive-overlay/src/TransitiveOverlay.story.js
packages/trip-viewer-overlay/package.json
packages/trip-viewer-overlay/src/TripViewerOverlay.story.tsx
packages/vehicle-rental-overlay/package.json
packages/vehicle-rental-overlay/src/VehicleRentalOverlay.story.tsx
packages/zoom-based-markers/package.json
packages/zoom-based-markers/src/ZoomBasedMarker.story.tsx
yarn.lock

This PR suggests a way to remove the somewhat "artificial" `forceMaxHeight` and `passedRef` props from the `BaseMap` component from #420, see if these changes are useful to you. (does not cover propagating changes to other packages, snapshots, and other refactors such as having a storybook-wide decorator for the various map overlays).

Vector tiles PR tweaks

---

packages/core-utils/package.json
packages/endpoints-overlay/package.json
packages/from-to-location-picker/package.json
packages/icons/package.json
packages/itinerary-body/package.json
packages/location-field/package.json
packages/route-viewer-overlay/package.json
packages/stop-viewer-overlay/package.json
packages/transit-vehicle-overlay/package.json
packages/transitive-overlay/package.json
packages/trip-details/package.json
packages/trip-form/package.json
packages/trip-viewer-overlay/package.json
packages/vehicle-rental-overlay/package.json
packages/zoom-based-markers/package.json
yarn.lock

This PR updates packages to use core-utils 7.0.0 and types 3.0.0. Patch releases should occur for all affected packages, except for core-utils that should not have a release
(The types dev dependency for core-utils is updated, but it is identical to the released one, so that does not change `.d.ts` files generated for core-utils.)

Update to coreutils 7

---

packages/core-utils/src/query.js

Edit: this seems to be blocked by #430.
A while ago we introduced "flex mode reducing". This feature allowed `core-utils` users to have a single mode `FLEX` which was automatically expanded/reduced to `FLEX_EGRESS,FLEX_ACCESS,FLEX_DIRECT`. 
This feature makes it really easy to add flex as a travel mode. However, it makes it difficult to use any of these OTP modes on their own. 
This PR makes this reduction optional, so that a user who wants to handle each OTP mode individually is able to. To remain backwards-compatible, the default behavior is the current behavior. Unit tests ensure that default behavior is unchanged.

Refactor Flex Reduction to be Optional

---

packages/base-map/package.json
packages/core-utils/package.json
packages/endpoints-overlay/package.json
packages/from-to-location-picker/package.json
packages/icons/package.json
packages/itinerary-body/package.json
packages/location-field/package.json
packages/park-and-ride-overlay/package.json
packages/printable-itinerary/package.json
packages/route-viewer-overlay/package.json
packages/stop-viewer-overlay/package.json
packages/stops-overlay/package.json
packages/transit-vehicle-overlay/package.json
packages/transitive-overlay/package.json
packages/trip-details/package.json
packages/trip-form/package.json
packages/trip-viewer-overlay/package.json
packages/vehicle-rental-overlay/package.json
packages/zoom-based-markers/package.json
yarn.lock

As part of the MapLibreGL upgrade, we need to update all internal dependencies. This PR also fully removes moment.

Update Internal Dependencies (Sep 2022)

---

packages/core-utils/src/__tests__/__mocks__/config.json
packages/core-utils/src/time.ts
packages/itinerary-body/src/__mocks__/config.json
packages/trip-details/package.json
packages/trip-details/src/TripDetails.story.tsx
packages/types/src/index.ts
yarn.lock

This PR deprecates fields and functions that use `longDateFormat` from the OTP configs and removes such references in tests. `longDateFormat` became unused after merging #281.
Requires #436 for CI tests to pass.

Remove longDateFormat

---

packages/transit-vehicle-overlay/package.json
yarn.lock

This PR unpins the icons version in the transit-vehicle-overlay package (prevents duplicate icons package downloads).

chore(deps): Unpin icons version in transit vehicle overlay.

---

packages/itinerary-body/src/AccessLegBody/mapillary-button.tsx
yarn.lock

This should fix the problem of the entirety of fa-solid being loaded into the otp-rr bundle.

refactor(itinerary-body): remove direct import of fa-solid

---

packages/types/src/index.ts

This PR updates types to include route text color attributes provided from OTP itinerary legs into transitive.

Add type support for route text color in itinerary leg and transitive

---

packages/core-utils/src/itinerary.ts

This PR fixes the return type for `itinerary.getLegBounds`.

fix(core-utils): Fix itinerary.getLegBounds return type.

---

packages/geocoder/src/__snapshots__/index.test.js.snap
packages/geocoder/src/geocoders/pelias.ts
packages/location-field/src/types.ts

#447 contained a bug which sent invalid requests to the geocoder. This PR resolves this oversight.

fix(geocoder): remove invalid layers from default layers list

---

packages/scripts/src/collect-i18n-messages.ts

This PR fixes the output of the `collect-i18n-messages.ts` script so that contents for each language appears in its own column (as opposed to concatenated).

fix(scripts): Separate language columns

---

README.md

This PR contains a now required mention of/link to Weblate as part of their open-source hosting plan, and adds an i18n overview section.

docs(README): Add i18n and Weblate overview [skip ci]

---

packages/trip-details/src/index.tsx
packages/trip-details/src/types.ts

There was previously no way to disable the calorie display in the trip details. This PR corrects this in a backwards compatible way (no prop specified = calories displayed)

Trip Details: make calorie display optional

---

packages/location-field/src/types.ts
packages/trip-details/src/index.tsx
packages/types/src/index.ts

This makes a change to the trip details package to use the co2 value included in the itinerary that is passed in from OTP-RR. That way this value only gets calculated once, higher up. The co2 property is added to the type to accommodate this change.

Trip-details use CO2 from Itinerary

---

packages/endpoints-overlay/src/endpoint.tsx
packages/endpoints-overlay/src/index.tsx
packages/endpoints-overlay/src/styled.ts
packages/location-field/src/types.ts

This PR adjusts the size of the endpoint icons to match the transit stop and rental place markers in the original transitive overlay, and cleans up the related CSS.

Adjust endpoint icon size

---

packages/route-viewer-overlay/src/index.tsx
packages/transitive-overlay/src/index.tsx
packages/transitive-overlay/tsconfig.json

The 200 units padding caused some problems on smaller screens where maplibre refused to update the bounds. This PR checks the screen width and only adds the padding if the window width is large enough to accommodate it.

fix: support bounds updating on small screens

---

packages/core-utils/package.json
packages/core-utils/src/__tests__/route.js
packages/core-utils/src/core-utils.story.tsx
packages/core-utils/src/route.ts
packages/location-field/src/types.ts
yarn.lock

This PR adds a new method to determine a readable text color for a background color. Rather than use standard benchmarks or methods, this method instead uses a carefully calibrated luminance based approach to "approve" color combinations that real agencies use (and that look appealing). The goal is to approve GTFS-based color combinations when they make sense, while being able to supply reasonable alternatives when the GTFS data is missing or of poor quality.
Use of Chroma. It's much smaller than tinycolor, but since otp-rr still uses tinycolor even after using this perhaps it makes more sense to use that larger library here? It's a 14kb pre-compression difference, so not sure if it's the biggest thing to worry about.

Core Utils: add text color generation

---

packages/base-map/src/index.tsx

Right clicking is not possible with a touch environment, so we fake it by handling long presses. The 600ms timeout is based on https://developer.android.com/reference/android/view/ViewConfiguration.html#getLongPressTimeout%28%29

fix(base-map): support onContextMenu in touch env

---

.github/workflows/codespell.yml

This PR excludes all i18n resources from codespell. This is done so we don't have to add language exclusions to `codespell.yml` each time someone adds a translation (via Weblate or regular PRs). This PR echoes https://github.com/opentripplanner/otp-react-redux/pull/686 and https://github.com/opentripplanner/otp-react-redux/pull/686#pullrequestreview-1160287923

ci(codespell): Exclude i18n folders from codespell.

---

packages/endpoints-overlay/package.json
packages/park-and-ride-overlay/package.json
packages/stop-viewer-overlay/package.json
packages/stops-overlay/package.json
packages/transit-vehicle-overlay/package.json
packages/vehicle-rental-overlay/package.json
packages/zoom-based-markers/package.json

This PR updates the base-map version for packages that use it's new `Popup` component that displays a shadow.
(Other packages that use the map but not the popups are not touched.)

Update base-map in pkgs that use its Popup or MarkerWithPopup.

---

packages/base-map/package.json
packages/core-utils/package.json
packages/endpoints-overlay/package.json
packages/from-to-location-picker/package.json
packages/icons/package.json
packages/itinerary-body/package.json
packages/location-field/package.json
packages/park-and-ride-overlay/package.json
packages/printable-itinerary/package.json
packages/route-viewer-overlay/package.json
packages/stop-viewer-overlay/package.json
packages/stops-overlay/package.json
packages/transit-vehicle-overlay/package.json
packages/transitive-overlay/package.json
packages/trip-details/package.json
packages/trip-form/package.json
packages/trip-viewer-overlay/package.json
packages/vehicle-rental-overlay/package.json
packages/zoom-based-markers/package.json
yarn.lock

The icons code splitting actually made things worse as it in some cases resulted in two different versions of the icons package being installed. This PR resolves this, while also updating all other internal dependencies.

Update Internal Dependencies (Nov 2022)

---

packages/core-utils/src/route.ts

The previous method of setting a fallback color didn't handle `null` correctly. This explicit `if` corrects this.

fix(core-utils/route.ts): support null text color

---

packages/core-utils/src/query.js

This PR resolves the infamous "am/pm" bug we've been seeing. Times such as `8:24` were being parsed as 8pm instead of 8am when the processing happened after 12pm because 12 hour time was being assumed. This PR corrects this.

fix(core-utils): prefer 24 hour time parsing

---

packages/route-viewer-overlay/__mocks__/mock-route-otp2.json
packages/route-viewer-overlay/__mocks__/mock-route2.json
packages/route-viewer-overlay/src/RouteViewerOverlay.story.js
packages/route-viewer-overlay/src/index.tsx

Partial fix for https://github.com/opentripplanner/otp-react-redux/issues/703.
With this PR, the calculation of the geometry for `map.fitBounds` is improved so that the "inner" region for rendering a route is based on the size of the map canvas and directly related to the size of the map canvas. This should reduce instances of "empty" render regions which previously prevented re-rendering when new route data is provided.
Also, explicit map updates are requested after `map.fitBounds` is called (otherwise, logging map bounds would often show the correct coordinates before the canvas is updated).

Fix route overlay rendering

---

packages/geocoder/src/apis/photon/index.ts
packages/geocoder/src/apis/photon/types.ts
packages/geocoder/src/geocoders/photon.ts
packages/geocoder/src/index.story.tsx
packages/geocoder/src/index.ts

Adds the photon geocoder
See https://github.com/opentripplanner/otp-react-redux/issues/706
Working as a proof of concept within otp-react-redux for autocomplete + reverse geocoding
[ ] Add search type (currently only autocomplete and reverse were tested)
[ ] Add bbox support
[ ] Support base URL overwrite (?)
[ ] Add more tests (?)
Also fixes a typo in the console.err message.

Add Photon Geocoder

---

packages/transitive-overlay/package.json
packages/transitive-overlay/src/index.tsx
packages/transitive-overlay/src/route-layers.ts
packages/transitive-overlay/src/util.ts
packages/types/src/index.ts

Blocked by/requires:
- #450
- #451
This PR improves route labels in the transitive overlay:
- horizontal rendering
- better background rendering
- better spacing of route labels when mutliple are rendered by maplibre-gl

Maplibre transitive route labels

---

packages/base-map/src/index.tsx
packages/base-map/src/util.ts
packages/base-map/tsconfig.json

This fix-release PR adds helper methods to compute padding of a mapbox `MapRef` and fit bounds on a map using the padding parameters and attempt forcing a redraw. Such methods are used in the route viewer (I want to reuse this with #485), trip viewer, and transitive overlays.

fix(base-map): Add helper methods to fit map to bounds

---

packages/core-utils/src/route.ts

We had a fix in place for when the text color was somehow invalid, but not one for when the background color is invalid. This PR fixes this.

fix(core-utils/route): avoid crash on gtfs with no background color

---

packages/geocoder/src/geocoders/abstract-geocoder.ts
packages/location-field/package.json
yarn.lock

Packages are only released if there is a `fix` commit.
This PR completes https://github.com/opentripplanner/otp-ui/pull/487
cc @amenk

Trigger Geocoder Package Release

---

packages/transitive-overlay/src/TransitiveOverlay.story.js
packages/transitive-overlay/src/index.tsx

Fix a regression introduced by #452, and future proof the handling of null transitive data input.

Support empty transitive data

---

packages/route-viewer-overlay/__mocks__/mock-flex-route2.json
packages/route-viewer-overlay/src/RouteViewerOverlay.story.js
packages/route-viewer-overlay/src/index.tsx

Attempt to fix #440.
I am missing mock data for the kind of route described in the linked issue, feel free to suggest if you have that handy.

fix(route-viewer-overlay): Fix auto-fitting of OTP2 flex routes.

---

packages/route-viewer-overlay/package.json
packages/route-viewer-overlay/src/RouteViewerOverlay.story.tsx
packages/route-viewer-overlay/src/index.tsx
packages/transitive-overlay/package.json
packages/transitive-overlay/src/TransitiveOverlay.story.tsx
packages/transitive-overlay/src/index.tsx
packages/trip-viewer-overlay/package.json
packages/trip-viewer-overlay/src/index.tsx

This PR updates the route, trip and transitive overlay packages to use the fit bounds methods from #488. This will also fix bounds fitting on mobile for the trip and transitive overlay packages.

Common fit bounds

---

packages/trip-details/src/TripDetails.story.tsx
packages/trip-details/src/index.tsx
yarn.lock

Community Transit wants to use the fare by leg table in their custom webapp, so we need this fare by leg table to be exported. (I thought it was already exported and I remember there being a story for it, any idea where that went?)

fix(trip-details): add export for fare by leg table

---

packages/core-utils/src/__tests__/itinerary.js
packages/core-utils/src/itinerary.ts

New method `itinerary.getDisplayedStopId` in core-utils, intended to be used in itinerary, printable itinerary packages, and in OTP-RR.

fix(core-utils): Extract utility method to compute a displayed stop id.

---

packages/route-viewer-overlay/src/index.tsx

Bounds fitting on the route viewer overlay still chokes if there is a large number of features rendered on the map, so in this PR, I am using a timeout before bounds fitting is triggered.

fix(route-viewer-overlay): Use timeout before fitting bounds

---

packages/trip-form/src/DateTimeSelector/index.tsx

this hides a use of 'document' from our SSR / yarn build, which otherwise complains about the use of an unknown (server-side) variable.

fix(SSR): isInputTypeSupported() and use of 'document' breaks TORA build

---

packages/base-map/src/index.story.tsx
packages/base-map/src/index.tsx

This PR adds support for multiple base layers. Configuration is done by allowing `baseLayer` to accept an array of strings instead of just a string.
A new prop `baseLayerNames` is added to allow the control to display pretty names. An alternative might be to use internationalization with the url as a key, but I think it's easier to push that responsibility up a level? Curious for others' thoughts.

Support Multiple Base Layers in BaseMap

---

packages/geocoder/src/geocoders/photon.ts

Reverse Geocoding with Photon does not show proper results when used with otp-react-redux (still coordinates are shown).
This should fix this issue - the returned point contains a field named "lon" not "lng", so lon was undefined here.

Fix Reverse Geocoding (follow up #487)

---

packages/trip-form/src/TripOptions.story.tsx
packages/trip-form/src/TripOptions/ModeRow.tsx
packages/trip-form/src/__mocks__/modes-en.ts

A bug exists in the `TripOptions` component for which if there is a category that has mixed modes (e.g. an option with mode "CAR_HAIL" and an option with mode "CAR_PARK") and the first option has non-null company attribute value the category is not given a default selection (i.e. there is no selection on the category when it is initially opened).  The change made to `ModeRow` resolves this issue.
I've also added a story to with mode data containing a category that reproduces this bug (when the fix is not applied) and did some clean up to TripOptions stories by creating and re-using a template and moving some default config into the default export

fix(trip-form): Give a default selection to all TripOptions categories

---

packages/itinerary-body/src/styled.tsx

This PR fixes the mis-alignment of items in the transit leg details (see screenshot).
It should maintain the relative position of the elevation chart and the walk/bike summary text.

Fix itin styles

---

packages/core-utils/src/itinerary.ts
packages/trip-details/src/types.ts
packages/types/src/index.ts

This PR adds a new type for mass units, and also a "looser" Itinerary type that makes all fields optional except legs, since in most places that is the only property we need. This will make Typescript happier when we are making "fake" itineraries in OTP-RR and in testing.

Improve Itinerary and CO2 Types

---

packages/itinerary-body/src/otp-react-redux/line-column-content.tsx
packages/transitive-overlay/src/util.ts

Sometimes we may want to use a non-gtfs mode type. However, this mode may still be a transit mode! This PR adds support for accepting this non-standard mode as a transit mode.

More lenient transit leg detection

---

packages/otp2-tile-overlay/src/index.tsx

The overlays had support for displaying themselves by default. With the new otp2 tile layer we lost this functionality! This PR resolves this, allowing any OTP2 tile layer to be set to be initially visible

fix(otp-tile-overlay): support enabling layers by default

---

packages/core-utils/src/itinerary.ts
packages/core-utils/tsconfig.json
packages/itinerary-body/src/__mocks__/itineraries/otp2-with-fareproducts.json
packages/trip-details/i18n/en-US.yml
packages/trip-details/src/TripDetails.story.tsx
packages/trip-details/src/fare-table.tsx
packages/trip-details/src/index.tsx
packages/trip-details/src/types.ts
packages/trip-details/src/utils.tsx
packages/types/src/index.ts

This PR adds support for the new fare by leg structure in OTP2. 
The fundamental thing to understand here is that each fare product used for a leg is stored under legProducts, along with the index of the leg it's associated with. An example itinerary was added to itinerary-body package for the story as well as to show an example of how it looks for review. 
This will be a lot more flexible in the future, and one way I took advantage of the new data is by adding a tooltip to the table cell explaining the transfer discount applied to a given fare. 
I tried to keep it so that in the future it will be easy to remove the OTP1 code. There is only one user of the OTP1 fare by leg, so once they upgrade, we can remove the code for that.

OTP2 FareProduct / Fare By Leg Support

---

packages/otp2-tile-overlay/src/index.tsx
packages/stops-overlay/src/index.tsx

This PR allows https://github.com/opentripplanner/otp-ui/pull/526 to be accessible outside of otp-ui.

Publish Internal Dependency Updates

---

packages/geocoder/src/apis/otp/index.ts
packages/geocoder/src/geocoders/otp.ts
packages/geocoder/src/index.story.tsx
packages/geocoder/src/index.ts
yarn.lock

OTP has a geocoder now! https://docs.opentripplanner.org/en/dev-2.x/sandbox/GeocoderAPI/
This PR lets you use it within otp-ui. Only the stops endpoint for now, as it would be a lot more work to get the rest of the layers to work (would have to parse the label strings) and they're not that high quality. ARCGIS provides better results without an API key.

Add OTP Geocoder

---

packages/location-field/src/index.tsx
packages/location-field/src/options.tsx
packages/location-field/src/styled.tsx

This PR improves a11y to the `LocationField` component, so that screen readers can indicate the active item when the user uses the up/down arrows to browse the list of suggested locations. This is done by using the `aria-activedescendant` attribute to the input field.

fix(location-field): Add aria-activedescendant attribute

---

packages/types/src/deprecated.ts
packages/types/src/index.ts
yarn.lock

This PR deprecates old types used for old mode selector code and adds new types to handle the new ModeButtons and other data such as the mode setting options.
The TransportMode type is based on the TransportMode type found in the GraphQL query.

Metro mode selector: Types

---

packages/map-popup/src/index.tsx

The map popup was sending backwards coordinates. This PR fixes this typo

fix(map-popup): correct typo in from/to picker

---

packages/itinerary-body/src/ItineraryBody/place-row.tsx
packages/itinerary-body/src/TransitLegBody/index.tsx
packages/itinerary-body/src/otp-react-redux/itinerary-body.ts
packages/itinerary-body/src/styled.tsx

The a11y updates to the itinerary body caused some regressions around styling, collapsing alerts, and the non otp-rr styling. This PR repairs all of this. Please let me know if I've missed anything!

Repair A11y `itinerary-body` Regressions

---

README.md
package.json
packages/endpoints-overlay/i18n/en-US.yml
packages/endpoints-overlay/i18n/fr.yml
packages/from-to-location-picker/i18n/en-US.yml
packages/from-to-location-picker/i18n/fr.yml
packages/itinerary-body/i18n/en-US.yml
packages/itinerary-body/i18n/fr.yml
packages/location-field/i18n/en-US.yml
packages/location-field/i18n/fr.yml
packages/map-popup/i18n/en-US.yml
packages/map-popup/i18n/fr.yml
packages/printable-itinerary/i18n/en-US.yml
packages/printable-itinerary/i18n/fr.yml
packages/transit-vehicle-overlay/i18n/en-US.yml
packages/transit-vehicle-overlay/i18n/fr.yml
packages/trip-details/i18n/en-US.yml
packages/trip-details/i18n/fr.yml
packages/trip-form/i18n/en-US.yml
packages/trip-form/i18n/fr.yml
yarn.lock

This PR adds `yaml-sort` to automatically sort modified YAML files (using A-Za-z) during the pre-commit stage.
`yaml-sort` will also reformat certain long strings and strip comments, so I have moved instructions to README and translation notes to Weblate ([see here for instance](https://hosted.weblate.org/translate/otp-react-redux/otp-ui-trip-form/en_US/?sort_by=-priority%2Cposition&offset=34)).

Perform yaml-sort on pre-commit

---

packages/trip-details/i18n/en-US.yml
packages/trip-details/i18n/es.yml
packages/trip-details/i18n/fr.yml
packages/trip-details/i18n/ko.yml
packages/trip-details/i18n/vi.yml
packages/trip-details/i18n/zh_Hans.yml
packages/trip-details/src/index.tsx
packages/trip-details/src/types.ts
packages/types/src/index.ts

This PR corrects the spelling of CO₂ to use the Unicode subscript.

Spell CO₂ using the Unicode subscript

---

packages/itinerary-body/src/__mocks__/itineraries/bike-transit-bike.json
packages/itinerary-body/src/__mocks__/itineraries/park-and-ride.json
packages/trip-details/i18n/en-US.yml
packages/trip-details/i18n/es.yml
packages/trip-details/i18n/fr.yml
packages/trip-details/i18n/ko.yml
packages/trip-details/i18n/vi.yml
packages/trip-details/i18n/zh_Hans.yml
packages/trip-details/src/index.tsx

Previous crash could happen if currency was missing, `cents` was missing, or if the entire fare object was missing. This PR allows for all those cases to occur.

Avoid Trip Details Crash on Missing Fare Info

---

packages/itinerary-body/src/defaults/access-leg-step.tsx
packages/itinerary-body/src/styled.tsx

Close #571. This PR adds distances to each walking leg step. Styles are configurable in that the styled components can be overridden. If we want explicit prop-based configuration, that can be added.

fix(itinerary-body): Add distances to access legs

---

.github/workflows/node-ci.yml
package.json
packages/scripts/src/validate-i18n.ts

This PR enforces that translations are available for English and French during CI (and during `yarn test`), and that no unused strings in those language files exist.

Enforce English and French content in CI

---

packages/itinerary-body/package.json
packages/trip-details/__mocks__/custom-english-messages.yml
packages/trip-details/i18n/en-US.yml
packages/trip-details/i18n/es.yml
packages/trip-details/i18n/fr.yml
packages/trip-details/i18n/ko.yml
packages/trip-details/i18n/nb_NO.yml
packages/trip-details/i18n/vi.yml
packages/trip-details/i18n/zh_Hans.yml
packages/trip-details/src/TripDetails.story.tsx
packages/trip-details/src/index.tsx
packages/trip-details/src/styled.ts
packages/trip-details/src/types.ts

Removes calorie counts and repurposes all methods with "Time Active" which combines time spent biking and walking to reflect the total number of minutes spent active in the trip duration.
BREAKING CHANGE: Calories removed and replaced by minutes active

Replace Calories with Minutes Active in Trip Details

---

packages/base-map/src/index.tsx
packages/base-map/src/styled.ts

This PR proposes the following fixes to the map layer selector:
- Same style and right margin as the zoom controls.
- Expanded layer selector contents appears above the zoom controls.
- Avoid most accidental activations of the first layer when opening the layer selector using touchscreens.

Map layer button fixes

---

README.md

Adds a badge for gitter (sharing a gitter room with OTP-RR) and one for the node-ci build.

refactor: add badges to readme

---

packages/route-viewer-overlay/__mocks__/mock-flex-route.json
packages/route-viewer-overlay/src/index.tsx
packages/route-viewer-overlay/src/util.ts

There was a previous bug where the overlay would attempt to center the map on non-existent data. This PR resolves this issue.

fix(route-viewer-overlay): fix crash on incomplete flex data

---

packages/core-utils/src/__tests__/query-params.ts
packages/core-utils/src/query-gen.ts

The current new mode selector generates invalid car-based modes. This PR repairs this, quite quickly and quite elegantly.

fix: new mode selector support car

---

packages/itinerary-body/src/TransitLegBody/alerts-body.tsx
packages/itinerary-body/src/__mocks__/itineraries/bike-rental-transit-bike-rental.json
packages/itinerary-body/src/__mocks__/itineraries/bike-transit-bike.json
packages/itinerary-body/src/__mocks__/itineraries/park-and-ride.json
packages/itinerary-body/src/__mocks__/itineraries/walk-transit-walk.json

OTP2 uses seconds instead of milliseconds to represent alert dates. This PR resolves alerts showing up as 1970

fix: alert timings in seconds instead of milliseconds, following OTP2

---

packages/stops-overlay/src/index.tsx

Trigger changes to incorporate https://github.com/opentripplanner/otp-ui/pull/599

feat(stops-overlay): support custom stop color

---

packages/itinerary-body/src/AccessLegBody/index.tsx
packages/itinerary-body/src/ItineraryBody/place-row.tsx

"access" legs as opposed to transit legs currently do not show stop information. This PR corrects this.

Show Stop code on non-stop Legs

---

packages/core-utils/src/query-gen.ts

Allows consumers to specify their own GraphQL query.

feat(core-utils/query-gen): add support for overriding graphql query

---

packages/core-utils/src/otpSchema.json
packages/core-utils/src/planQuery.graphql
packages/itinerary-body/src/TransitLegBody/index.tsx
packages/types/src/index.ts

This PR adds stop sequence support when using the new GraphQL API.

GraphQL Trip Stop Sequence Support

---

packages/trip-form/src/MetroModeSelector/MetroModeSelector.story.tsx
packages/trip-form/src/MetroModeSelector/SubSettingsPane.tsx
packages/trip-form/src/MetroModeSelector/index.tsx

This PR does two things:
- Disables the hover element if there are no sub settings to be displayed.
- Uses flexbox to fix weird wrapping that was happening on long mode settings

Small mode selector enhancements

---

packages/itinerary-body/src/__mocks__/itineraries/walk-only.json
packages/itinerary-body/src/defaults/access-leg-step.tsx

This is invalid and should never be returned, but just in case it is, this PR allows it to render correctly

Support Step Length 0

---

packages/core-utils/src/__tests__/__mocks__/fare-products-itinerary.json
packages/core-utils/src/__tests__/itinerary.js
packages/core-utils/src/itinerary.ts

This PR allows core-utils to handle null ID values in fare products which can be returned by OTP on instances without specific fare modules. (GTFS fares)

Handle null fareproduct IDs in core-utils

---

packages/endpoints-overlay/package.json
packages/icons/package.json
packages/itinerary-body/package.json
packages/location-field/package.json
packages/map-popup/package.json
packages/otp2-tile-overlay/package.json
packages/park-and-ride-overlay/package.json
packages/printable-itinerary/package.json
packages/route-viewer-overlay/package.json
packages/stop-viewer-overlay/package.json
packages/stops-overlay/package.json
packages/transit-vehicle-overlay/package.json
packages/transitive-overlay/package.json
packages/trip-details/package.json
packages/trip-form/package.json
packages/trip-viewer-overlay/package.json
packages/vehicle-rental-overlay/package.json
packages/zoom-based-markers/package.json

Need to get the new core utils version into trip details, thought I'd update everything along the way. 
FYI: With new Yarn we can use the `workspace:` protocol and no longer do these PRs.

Update Internal Dependencies (especially trip-details)

---

packages/geocoder/src/index.ts

A PR so that the geocoder config type can simply be imported as
```js
import { GeocoderConfig } from "@opentripplanner/geocoder";
```

fix(geocoder): Export GeocoderConfig type in package index.

---

packages/otp2-tile-overlay/src/Otp2TileOverlay.story.tsx
packages/otp2-tile-overlay/src/index.tsx
packages/otp2-tile-overlay/src/util.ts

Pass custom config color into OTP2 map layers.

refactor: pass otp2 custom config colors

---

packages/core-utils/src/__tests__/itinerary.js
packages/core-utils/src/itinerary.ts

This fixes fares being counted multiple times when a fare module doesn't provide per-leg fares.

Handle fareproduct use IDs correctly

---

packages/itinerary-body/src/AccessLegBody/mapillary-button.tsx
packages/itinerary-body/src/styled.tsx

This PR polishes the spacing for items that follow a transit stop location header (see screenshot. Left: before; right: after).

Fix transit leg spacing

---

packages/itinerary-body/src/defaults/line-column-content.tsx
packages/types/src/index.ts
yarn.lock

This PR adds missing OTP2 leg route attributes to the `Leg` type (see the graphql query template for details).
Should create a fix release for the types package, and no release to the itinerary-body package (that will be handled separately).

Add OTP2 advanced leg route attributes

---

packages/trip-form/src/MetroModeSelector/index.tsx

Very excited about this fix for opening a dropdown triggering a `mouseOut` event in Firefox.

fix(trip-form): fix dropdown/hover bug in firefox

---

packages/core-utils/src/__tests__/__snapshots__/query-params.ts.snap
packages/core-utils/src/__tests__/__snapshots__/query.js.snap
packages/core-utils/src/otpSchema.json
packages/core-utils/src/planQuery.graphql
packages/core-utils/src/query-gen.ts
packages/core-utils/src/query-params.js
packages/core-utils/src/query.js

BREAKING CHANGES:
- `trip.tripHeadsign` is no longer returned by the plan queries made by query-gen.
- walk speed parameters are removed from `queryParams`.
This PR retrieves `leg.headsign` instead of `trip.tripHeadsign`, and passes a new `walkspeed` parameter in the query-gen `plan` GraphQL query.
Per https://github.com/opentripplanner/OpenTripPlanner/pull/5205, `leg.headsign` should contain the applicable stop headsign or trip headsign value if provided.

Add walkspeed, leg.headsign to GraphQL plan query, remove trip.tripHeadsign

---

packages/printable-itinerary/src/tnc-leg.tsx

This PR fixes a runtime compilation error.

fix(printable-itinerary): Import parseOTP2Minute from the correct folder

---

packages/core-utils/src/itinerary.ts

This PR populates the `agencyId` of an itinerary from graphql responses, for use in determining agency logos in itinerary-body.

fix(core-utils): Set agencyId when converting graphql resp to legacy.

---

packages/core-utils/package.json
packages/core-utils/src/query-gen.ts
packages/types/src/index.ts
yarn.lock

This PR allows a `falseValue` to be set in a checkbox mode setting, which will allow us to override the OTP default value for unchecked options.

Allow false value in mode setting

---

packages/core-utils/package.json
packages/core-utils/src/ui.ts
packages/location-field/src/options.tsx
yarn.lock

This PR removes IE11 support. OTP-UI has not worked with IE11 for a while now, but for some reason we still had some compatibility code in there. 
This PR also cleans some other dependencies and runs yarn deduplicate, which should help with bundle sizes

Cleanup yarn.lock, Remove IE11

---

packages/itinerary-body/src/util.ts

I think this is a regression... This method was only reading OTP1 type place names. This PR adds OTP2 support. A future PR will be needed to get this fix into the map components. 
This fixes rental bikes showing up as "Default vehicle type" and instead uses the company name.

Itinerary Body Support OTP2 Place Names

---

packages/location-field/i18n/en-US.yml
packages/location-field/src/index.tsx
packages/location-field/src/options.tsx
packages/location-field/src/styled.ts

Adjust markup for location field so that typeahead results from geocoder are read to AT (specifically voiceover)
Note for testing that Voiceover is only officially supported on safari!!

Typeahead Results on Voiceover

---

packages/core-utils/src/itinerary.ts
packages/core-utils/src/query.js
packages/trip-form/src/MetroModeSelector/MetroModeSelector.story.tsx
packages/trip-form/src/MetroModeSelector/SubSettingsPane.tsx
packages/trip-form/src/MetroModeSelector/index.tsx
yarn.lock

This PR fixes vertical alignment of transit mode icons and text when a mode name that spans over two lines is next to a mode with a 1-line name.
This PR also fixes the expand button size for keyboard access.
| Before | After |
|---|---|
| ![before screenshot](https://github.com/opentripplanner/otp-ui/assets/56846598/cd059528-d3f4-4ef8-ab57-70ded951dd14) | ![after screenshot](https://github.com/opentripplanner/otp-ui/assets/56846598/b945519f-14c4-4c94-bc4c-6ad596a4b928) |

fix(mode-selector): Fix vert alignment of transit modes

---

packages/trip-form/src/MetroModeSelector/SubSettingsPane.tsx

This PR follows up on #664 with transit option alignment fixes for Safari.

fix(trip-form): Fix submode selector alignment in Safari.

---

packages/core-utils/src/itinerary.ts
packages/core-utils/src/planQuery.graphql

Adds the `gtfsId` to the graphQL route object, and replaces the route id in `convertGraphQLResponseToLegacy`

feat(core-utils): Add gtfsId to GraphQL query

---

packages/core-utils/src/planQuery.graphql

The agency id we get at the moment is generated. This PR uses the real one instead

Get real agency id in graphql plan request

---

packages/itinerary-body/src/TransitLegBody/index.tsx

This fixes a crash happening sometimes when there is no latestBookingTime.

fix(ItineraryBody): fix crash on no latestBookingTime

---

packages/building-blocks/package.json
packages/trip-details/src/fare-table.tsx
packages/trip-details/src/index.tsx
yarn.lock

This is a fix that enables the fare table to function correctly when fares are $0. Previously these were assumed to be equal to undefined, and they were hidden. But we now have the ability to pass back actual undefined fares in the API, so it's time to correct this in the UI.

fix(trip-details): show fares of $0

---

packages/core-utils/src/planQuery.graphql

An oversight prevented leg-based alerts from rendering. this PR rectifies this.

Correctly Request Alerts in GraphQL Query

---

packages/types/src/index.ts
yarn.lock

This PR adds the necessary properties to the types for the nearby view.

Nearby view support (types)

---

packages/itinerary-body/i18n/en-US.yml
packages/itinerary-body/i18n/fr.yml
packages/itinerary-body/i18n/i18n-exceptions.json
packages/itinerary-body/src/ItineraryBody/accessibility-rating.tsx
packages/itinerary-body/src/ItineraryBody/place-row.tsx

Provides invisible labeling for wheelchair accessibility badges so that users with AT can identify whether a leg or itinerary is wheelchair accessible.
See discussion on #675, closed due to mishandled merge

Wheelchair accessible labeling

---

packages/itinerary-body/src/AccessLegBody/index.tsx
packages/itinerary-body/src/TransitLegBody/index.tsx
yarn.lock

The itinerary body previously showed carets when they were inoperable. This PR ensures they are only shown when it makes sense

Itinerary Body Caret Improvements

---

packages/types/src/index.ts

Cherry-picked from https://github.com/opentripplanner/otp-ui/pull/672 so we can get a stable version of it. Adds support for an array of `TransportMode`

Change addTransportMode type

---

packages/core-utils/package.json
packages/core-utils/src/query-gen.ts
packages/otp2-tile-overlay/package.json
packages/stops-overlay/package.json
packages/trip-form/package.json
yarn.lock

Remove dependencies on the alpha branch.

fix(deps): remove alpha dependencies

---

packages/printable-itinerary/src/transit-leg.tsx

Temporary patch to support null route objects until we figure out how we want to handle it inside of core utils

Support Null Route Object (Printable Itinerary)

---

packages/trip-form/src/MetroModeSelector/SubSettingsPane.tsx
packages/trip-form/src/index.ts

We need the mode setting renderer to show custom mode setting options in calltaker, whose options panel is not in OTP UI. This allows us to reuse this renderer.

feat(trip-form): expose mode setting renderer

---

packages/core-utils/src/planQuery.graphql

The from/to fields in the plan query needed lat lon information. 
Currently in use via alpha branch in nearby-view PR.

fix(core-utils): adds position information to stop query

---

packages/itinerary-body/src/stories/itinerary-body-defaults-wrapper.tsx

we treated a value that is optional as non optional. this is now corrected

Fix Crash on Missing Route Data (itin-body)

---

packages/core-utils/src/itinerary.ts
packages/itinerary-body/src/util.ts
packages/map-popup/src/util.ts

We had some override techniques in place, but nothing will be as reliable as this for removing that silly string!

itinerary body: never display `“default vehicle type” `

---

packages/geocoder/src/apis/otp/index.ts
packages/geocoder/src/geocoders/otp.ts

The OTP geocoder response was not correctly implemented. `stop.code` is optional. This means we were sometimes rendering `(undefined)`. This PR corrects this mistake.

fix(geocoder/otp): correctly accept `stop.code` as optional

---

packages/icons/src/icon-renderer.js
packages/icons/src/leg-icon.js
packages/icons/src/stories/classic-mode-icon.story.js
packages/icons/src/stories/custom-mode-icon-renderer.js
packages/icons/src/stories/custom-mode-icon.js
packages/trip-details/package.json

In some cases, `ModeIcon` requires the `leg` prop, but `ClassicIcon` does not pass it. This fixes that!

fix(icons): Pass leg prop from classicicon to modeicon

---

packages/trip-form/src/MetroModeSelector/utils.ts
packages/trip-form/src/__tests__/__snapshots__/mode-selector-utils.js.snap
packages/trip-form/src/__tests__/mode-selector-utils.js
packages/trip-form/src/index.ts
packages/trip-form/tsconfig.json
packages/types/src/index.ts

In cases where there are route mode overrides in the config, we'll use the banned parameter to exclude routes under a custom submode. This adds a util function to generate a list of banned routes based on the mode settings and route mode overrides.

Banned routes generator

---

packages/transit-vehicle-overlay/src/VehicleTooltip.tsx
packages/transit-vehicle-overlay/src/index.tsx

Makes the transit vehicle overlay use the long name if the route short name isn't available. This saves us from using a hack in OTP-RR to make the tooltip show up for agencies that don't publish a short name.

Transit vehicle overlay show longname

---

packages/geocoder/src/apis/otp/index.ts
packages/geocoder/src/geocoders/otp.ts

Support for https://github.com/opentripplanner/OpenTripPlanner/pull/5634
No localization, but I think this is fine since there are no English words and all the GTFS will be non-localized anyway

fix: support new OTP geocoder `agencies` field

---

packages/vehicle-rental-overlay/src/index.tsx

Previously the zoom was only being checked on render. This means if you didn't click anything the layer wouldn't update and the cool ferris wheel behavior functioned very strangely. By moving zoom state into react state we do things more sensibly. Most importantly, the zoom behavior is fixed!

Vehicle Overlay: Fix zoom bug fix

---

packages/vehicle-rental-overlay/src/index.tsx

The map zooming was a bit laggy when zooming around but this fixes it by pulling zoom data from the event rather than from up the react tree

fix(vehicle-rental-overlay): fix laggy zooming with vehicle overlay

---

packages/vehicle-rental-overlay/src/index.tsx

Whoops! We accidentally published some code that didn't correctly read the zoom level. This PR reads it correctly. I checked the story, I checked it with otp-rr. I also lowered the UI adjustment threshold to improve performance

vehicle rental overlay: avoid crash on missing event param

---

packages/location-field/src/index.tsx

Location Field loved to show users that annoying AbortError that was triggered by them making a new request! This PR resolves this

fix: don’t show users `abortError`

---

packages/transitive-overlay/src/route-layers.ts

Small fix to only show background for transitive route name badge if we are passing a route name.
| Before | After |
|--------|-------|
|![image](https://github.com/opentripplanner/otp-ui/assets/115499534/6cb9c946-230c-411e-bf57-8c6e21d86941)|![image](https://github.com/opentripplanner/otp-ui/assets/115499534/c95d77c7-b07f-4706-bae1-425d90bc07d7)|

Only render routeName badge when routeName exists

---

.storybook/react-intl.js
packages/base-map/i18n/en-US.yml
packages/base-map/i18n/es.yml
packages/base-map/i18n/fr.yml
packages/base-map/i18n/i18n-exceptions.json
packages/base-map/i18n/ko.yml
packages/base-map/i18n/ru.yml
packages/base-map/i18n/tl.yml
packages/base-map/i18n/vi.yml
packages/base-map/i18n/zh_Hans.yml
packages/base-map/src/index.tsx
packages/base-map/src/mapControlLocale.tsx

Passes translated strings to MapLibre to override their default map controls.

feat(base-map): Add support for i18n on map controls

---

packages/transit-vehicle-overlay/src/index.tsx
packages/types/src/index.ts

RT Vehicle updates have a lastUpdated field that we previously always ignored. This sometimes resulted in a bunch of busses piling up in the yard because they hadn't sent an update in forever. This PR introduces a new prop that can be used to hide vehicles that haven't updated their location in a certain amount of time
cc @fpurcell

fix: support `maxVehicleAge` realtime vehicle filtering based on last update

---

packages/geocoder/src/apis/otp/index.ts
packages/geocoder/src/geocoders/otp.ts

Right now it causes crashes. We use autocomplete to achieve the same behavior

Support `search` for OTP Geocoder

---

packages/geocoder/package.json
packages/otp2-tile-overlay/src/Otp2TileOverlay.story.tsx
packages/otp2-tile-overlay/src/index.tsx
packages/otp2-tile-overlay/src/util.ts
yarn.lock

This add support for the new OTP areaStops layer. I feel like implementation is not perfect. Looking for advice

fix: add `areaStops` layer support

---

packages/location-field/src/styled.ts

Set a max-height on the location field results so that users can scroll in cases where the list is too long

fix(location-field): Add overflow to results container

---

packages/itinerary-body/i18n/en-US.yml
packages/itinerary-body/i18n/fr.yml
packages/itinerary-body/src/TransitLegBody/alerts-body.tsx
packages/itinerary-body/src/TransitLegBody/index.tsx
packages/itinerary-body/src/styled.tsx

- Creates a `ul` and `li` for each transit alert
- Creates a clear alert hyperlink that opens in external window (if url is provided)
- Adds more invisible context for AT

feat(itinerary-body): Fix alerts a11y

---

packages/core-utils/src/query-gen.ts

We even have this in our plan query file! How did we not support setting this!

fix(core-utils): support `unpreferred` query param

---

packages/itinerary-body/src/defaults/access-leg-description.tsx
packages/types/src/index.ts

The itinerary body walk legs currently show distance. If a user wants to override the string to display duration instead, they'll need that value. Sadly, it's only in seconds. To fix this, we need a formatDuration method. That method needs to be passed in. Therefore this PR is quite large for doing functionally nothing, but it opens the door to exciting features in the future

fix(itin-body): support duration in walk leg string override

---

packages/otp2-tile-overlay/src/index.tsx

Sometimes stops are a part of stations. OTP now exposes this, so we can filter them out.

fix: don’t show stops that are within stations

---

packages/map-popup/i18n/en-US.yml
packages/map-popup/i18n/es.yml
packages/map-popup/i18n/fr.yml
packages/map-popup/i18n/ko.yml
packages/map-popup/i18n/nb_NO.yml
packages/map-popup/i18n/ru.yml
packages/map-popup/i18n/tl.yml
packages/map-popup/i18n/tr.yml
packages/map-popup/i18n/vi.yml
packages/map-popup/i18n/zh_Hans.yml
packages/map-popup/src/MapPopup.story.tsx
packages/map-popup/src/__snapshots__/MapPopup.story.tsx.snap
packages/map-popup/src/index.tsx
packages/map-popup/src/util.ts

It was a little confusing that there was no title in the station names. Especially when feeds had terrible station names. We resolve this. As a result we remove company name from the other strings. However, the car isn't localized, so it's kept for now. In the future we might want to get rid of that

Map Popup show company name in all map popup titles

---

packages/building-blocks/src/dropdown/index.tsx
packages/building-blocks/src/focus-trap-wrapper/dom-query.ts
packages/building-blocks/src/focus-trap-wrapper/index.tsx
packages/building-blocks/src/stories/__snapshots__/focusTrapStory.story.tsx.snap
packages/building-blocks/src/stories/focusTrapStory.story.tsx

Housing Focus Trap Wrapper in map popup doesn't make a ton of sense and is causing circular dependencies and duplicated code.
This version of focus trap also allows for some configuration of which elements are focusable within the trap. For example, if you're creating non-standard focusable elements with `tabIndex`, those can be included.

feat(building-blocks): add focus trap to building blocks

---

packages/geocoder/src/geocoders/otp.ts

Instead of picking the first agency (randomly selected) we instead look at other factors to generate an excellently fitting agency name.

fix(geocoder/otp): more clever agency name selection

---

packages/building-blocks/src/focus-trap-wrapper/index.tsx
packages/building-blocks/src/index.ts

Focus trap wrapper is going to be the death of me. Fixes #765 which creates the `FocusTrapWrapper` without actually exporting it!!

fix(building-blocks): actually export focus trap wrapper

---

packages/otp2-tile-overlay/src/index.tsx

Adds a new prop to the OTP2 tile layer to support a stop whitelist. If this prop is active, only stops with this id will be shown. Zoom level is also overridden.

Support stop filtering

---

packages/map-popup/src/__snapshots__/MapPopup.story.tsx.snap
packages/map-popup/src/index.tsx
packages/otp2-tile-overlay/src/index.tsx

Fixes IDs that are breaking due to stop codes, passes `closePopup` to `MapPopup` through `otp2-tile-layer`, prevent crash on null `closePopup`

Fix Map Popups (and focus traps)

---

packages/core-utils/src/itinerary.ts

This adds a new function (to avoid a breaking change) that checks for transit legs using the OTP2 `transitLeg` property. We could add extra functionality to this in the future to check for transit legs.
To avoid breaking changes in the future, is there any chance that we would want to support other arguments or return types in the future?

feat(core-utils): add isTransitLeg function that uses transitLeg prop

---

packages/map-popup/src/MapPopup.story.tsx
packages/map-popup/src/__snapshots__/MapPopup.story.tsx.snap
packages/map-popup/src/index.tsx
packages/otp2-tile-overlay/src/index.tsx

Pass the `getEntityPrefix` function that brings transit operator logos into `map-popup` by way of the tile overlay.

Pass operator logos to map popup

---

packages/otp2-tile-overlay/src/index.tsx

The line around areas wasn't being filtered! oh no!

fix: add missing `minzoom` to area border

---

.storybook/main.js
packages/base-map/package.json
packages/building-blocks/package.json
packages/endpoints-overlay/package.json
packages/icons/package.json
packages/itinerary-body/package.json
packages/location-field/package.json
packages/map-popup/package.json
packages/otp2-tile-overlay/package.json
packages/park-and-ride-overlay/package.json
packages/printable-itinerary/package.json
packages/route-viewer-overlay/package.json
packages/stop-viewer-overlay/package.json
packages/stops-overlay/package.json
packages/transit-vehicle-overlay/package.json
packages/transitive-overlay/package.json
packages/trip-details/package.json
packages/trip-form/package.json
packages/trip-viewer-overlay/package.json
packages/vehicle-rental-overlay/package.json
packages/zoom-based-markers/package.json
yarn.lock

The master branch is completely messed up, so we need to use an alpha build to fix it. After this PR is merged we can eliminate the alpha dependency. 
we don't need a semantic release fix commit because it will release based on previous commits already in master once the build succeeds.

fix build issues by using alpha version

---

packages/endpoints-overlay/src/EndpointsOverlay.story.tsx
packages/endpoints-overlay/src/index.tsx

In response to https://github.com/opentripplanner/otp-react-redux/pull/1272#discussion_r1779001128 , this PR makes the `setLocation` prop in the `EndpointsOverlay` optional (puts in the default `noop` handler as with other event handlers).

fix(EndPointsOverlay): Make setLocation optional

---

packages/endpoints-overlay/package.json
packages/park-and-ride-overlay/package.json
packages/vehicle-rental-overlay/package.json

Someone noticed that we have some old react-dom versions in our packages. This is bad! We need to get all those in sync with the react version (which is 18).

deps: update react-dom

---

packages/otp2-tile-overlay/src/index.tsx

Requires a few hacks to get click handling working, but allows us to render stations/stops seamless as one layer

fix: add combined stops/stations layer

---

packages/itinerary-body/src/ItineraryBody/place-row.tsx
packages/itinerary-body/src/stories/__snapshots__/OtpRrItineraryBody.story.tsx.snap
packages/itinerary-body/src/stories/__snapshots__/OtpUiItineraryBody.story.tsx.snap

Adds some class names that are helpful when styling

fix(itinerary-body): indicate rented bikes in class name

---

packages/itinerary-body/src/__mocks__/itineraries/otp2-transit-leg.json
packages/transitive-overlay/src/TransitiveOverlay.story.tsx
packages/transitive-overlay/src/util.ts

This PR adds support for OTP2 leg routes, so that route colors and names from OTP2-returned itineraries render correctly. A new mock is added to itinerary-body but that's only for Storybook for transitive-overlay (i.e. dev and test time), so no new package release for itinerary-body will be created.
I have removed map coordinates and zoom from transitive-overlay stories as these story parameters don't seem to affect rendering - the map is autofitted when a new itinerary is rendered.

OTP2 route support in Transitive

---

packages/trip-form/src/MetroModeSelector/SubSettingsPane.tsx

Uses `setTimeout` to wait for the mode button animation to complete before setting submode options to their default values.

fix(trip-form): close mode button before setting submode options to default

---

packages/transit-vehicle-overlay/src/index.tsx

fix(transit-vehicle-overlay): use correct+consistent time units

---

packages/building-blocks/src/stories/__snapshots__/alerts.story.tsx.snap
packages/itinerary-body/src/ItineraryBody/index.tsx
packages/itinerary-body/src/ItineraryBody/place-row.tsx
packages/itinerary-body/src/TransitLegBody/alerts-body.tsx
packages/itinerary-body/src/TransitLegBody/index.tsx
packages/itinerary-body/src/stories/OtpRrItineraryBody.story.tsx
packages/itinerary-body/src/stories/__snapshots__/OtpRrItineraryBody.story.tsx.snap
packages/itinerary-body/src/stories/itinerary-body-defaults-wrapper.tsx
packages/itinerary-body/src/types.ts

Make the 'Effective as of [date]' line from the alert message configurable, as requested from the client.

feat(itinerary-body): add and use showAlertEffectiveDateTimeText to alert components

---

packages/itinerary-body/src/TransitLegBody/alerts-body.tsx

This PR imports a single icon from fa-solid instead of "requiring" the entire library. This change can help reduce the main OTP-RR production bundle size by as much as 2+MB! (See screenshot before/after)

fix(itinerary-body): Optimize icon import in AlertsBody.

---

.github/workflows/node-ci.yml

Ubuntu 24.04 is supported by a newer version of Playwright, but not the one we are using

downgrade ubuntu until playwright is upgraded

---

package.json
packages/transitive-overlay/src/index.tsx

This pull request addresses a need for Trimet's instance of the maplibre map to not get the camera's placement hijacked by the _zoomToGeoJSON_ method which is causing some issues with how we want to frame the transitive-overlay with respect to the side-panel we house much of our tools in.
Essentially, we pass in _boundsFitting_ from the client and into packages/transitive-overlay/src/index.tsx. If it happens to be **false** then when _zoomToGeoJSON_ is called then it returns immediately with no effect on the map. Since this was set up to be active by default, I made the _boundsFitting_ prop be defaultly **true**.

Add 'boundsFitting' prop to manage camera manipulation via zoomToGeoJSON method

---

packages/endpoints-overlay/i18n/en-US.yml
packages/endpoints-overlay/i18n/fr.yml
packages/endpoints-overlay/src/EndpointsOverlay.story.tsx
packages/endpoints-overlay/src/endpoint.tsx
packages/endpoints-overlay/src/index.tsx

Pass ability to `setViewedStop` to endpoint layer, so user can see it in the nearby view.
Maybe the string should be "Open in nearby view" instead of "View in nearby view"? Which one makes more sense?

Set viewed stop from endpoint

---

packages/trip-form/src/MetroModeSelector/AdvancedModeSettingsButton/index.tsx
packages/trip-form/src/MetroModeSelector/__snapshots__/AdvancedModeSettingsButton.story.tsx.snap

We were generating the mode label translation and forgetting to apply it to the actual mode button whoops

fix(trip-form): apply translation to mode label

---

packages/geocoder/src/geocoders/pelias.ts
packages/geocoder/src/test-fixtures/pelias/autocomplete-response.json
yarn.lock

It seems like we've been seeing some exact duplicates coming back from Pelias in some cases. This PR removes them.
This will slow things down, but hopefully not too much.

Geocoder: Pelias: remove exact duplicates

---

packages/itinerary-body/src/TransitLegBody/alerts-body.tsx
packages/itinerary-body/src/stories/__snapshots__/OtpRrItineraryBody.story.tsx.snap

When `showAlertEffectiveDateTimeText` is false, still show alert urls.

fix(itinerary-body): show alert links if showAlertEffectiveDateTimeText is false

---

packages/core-utils/src/query-gen.ts
packages/core-utils/src/time.ts

Creates a util to round a leg duration up to at least one minute (to prevent small durations from being shown as 0 min)
Based off discussion in https://github.com/opentripplanner/otp-ui/pull/816
I also updated the query gen file to apply [this feedback](https://github.com/opentripplanner/otp-react-redux/pull/1366#discussion_r2001325156), since I got the idea for the `ValidModeCombo` check in that PR from `isCombinationValid`

Add ensureAtLeastOneMinute util 

---

packages/geocoder/src/apis/otp/index.ts
yarn.lock

This makes it easier to search for stop codes without getting street addresses mixed in

fix(otp geocoder): don’t send “stop id ” to otp

---

package.json
packages/otp2-tile-overlay/src/index.tsx

Allows implementers to define a minZoom override, to avoid being stuck with `14`.

OTP2 Tilelayer MinZoom Support 

---

packages/base-map/src/index.tsx

Trying to print the printable itinerary in firefox resulted in the map being empty. Added `preserveDrawingBuffer` per this  thread  https://github.com/mapbox/mapbox-gl-js/issues/9810
| Before | After |
|--------|-------|
|![image](https://github.com/user-attachments/assets/66457f45-b797-4c55-abba-4681255e4ecc)|![image](https://github.com/user-attachments/assets/55fda45b-940d-4330-81a0-4a0de0206033)|

fix(base-map): fix firefox printing bug

---

packages/geocoder/src/apis/otp/index.ts

We forgot to `toLowerCase` in one place! Which caused a bug. This bug is here fixed

Correctly Lowercase "stop id"

---

packages/location-field/src/index.tsx

Fixes a bug where the user has text in the location field, moves the map and the locations changes, but the message still reflects the old location.

fix(location-field): set message to null when location changes

---

packages/location-field/src/index.tsx

Address a bug to clear geocoder results when there is no text in the search bar.

fix(location-field): if no user text then clear geocoder results

---

packages/geocoder/package.json
packages/location-field/src/index.tsx
packages/location-field/src/stories/__snapshots__/Desktop.story.tsx.snap
packages/location-field/src/stories/__snapshots__/Mobile.story.tsx.snap

Splitting the geocoded features into categories broke the way we applied `itemIndex` to the list of menu items, which subsequently broke keyboard navigation. Instead of tracking the options by index, and also using a location function lookup, now we use `indexedOptionLookup` to create an array of all the ids and location handlers, and use that to iterate through the options in `onKeyDown`
Also added `generateOptionId` to create bespoke consistent ids for each element (open to feedback on this, it's pretty hacky)

fix(location-field): Fix keyboard navigation

---

packages/types/src/index.ts

This is meant to be step one of a two part pull-request situation.
This adds an optional value to the _Place_ type:
```
vehicleRentalStation?: { rentalNetwork: { networkId: string } };
```
The follow up pull request will add the following code in  the getCompanyFromLeg method in _core-utils/src/itinerary.ts_
```
if (from.vehicleRentalStation && from.vehicleRentalStation.rentalNetwork) {
return from.vehicleRentalStation.rentalNetwork.networkId;
}
```
And all of this is so that in our client-code at Trimet, we can avoid having to do the following:
```
const company =
coreUtils.itinerary.getCompanyFromLeg(leg) ||
leg.from.vehicleRentalStation?.rentalNetwork.networkId;
```
and instead just have this:
```
const company = coreUtils.itinerary.getCompanyFromLeg(leg);
```

fix: Add new optional property to Place type

---

scripts/pack-and-extract-single.sh

Clean up the temporary directory before extracting the tar to eliminate problems when the version changes or files are removed.

fix: Clean up temporary directory

---

packages/location-field/src/index.tsx
packages/location-field/src/stories/__snapshots__/Desktop.story.tsx.snap
packages/location-field/src/stories/__snapshots__/Mobile.story.tsx.snap

Adds `type=button` to the location field button for better keyboard navigation control.

fix(location-field): add type to location field button for better keyboard nav control

---

packages/location-field/src/index.tsx
packages/location-field/src/stories/__snapshots__/Desktop.story.tsx.snap
packages/location-field/src/stories/__snapshots__/Mobile.story.tsx.snap

Fixes the clear button so it wont default to `type='submit'` when within a form

fix(location-field): add type to location field clear button

---

packages/trip-details/src/components/fares.tsx
packages/trip-details/src/types.ts

We don't need the header key here because it was just used on the old fare display which we don't really use anymore.

Trip Details make header key optional on default fare type

---

packages/trip-form/i18n/en-US.yml
packages/trip-form/i18n/fr.yml
packages/trip-form/src/MetroModeSelector/AdvancedModeSettingsButton/index.tsx
packages/trip-form/src/MetroModeSelector/__snapshots__/AdvancedModeSettingsButton.story.tsx.snap

Checkboxes do not support `aria-expanded` so add an additional string to the `aria-label` to include whether an option has expanded suboptions

Alert AT that subsettings are expanded in transit options

---

packages/map-popup/src/MapPopup.story.tsx
packages/map-popup/src/__snapshots__/MapPopup.story.tsx.snap
packages/map-popup/src/index.tsx
packages/map-popup/src/util.ts
packages/otp2-tile-overlay/src/index.tsx

This PR adds support for rendering the agency name, stop code, and stop name in the map popup used in otp2 tile overlay. It does this by accepting a prop containing a mapping of stop IDs to agencies, since this information is not available in the vector tile data. It also provides a callback prop so the component can tell its parent when a stop has been clicked on and the data is needed. 
Paired with https://github.com/opentripplanner/otp-react-redux/pull/1433

feat: add support for rendering agency name with the stop name in map popup

---

packages/park-and-ride-overlay/src/index.tsx
packages/transit-vehicle-overlay/src/index.tsx

This PR adds two breaking-change commits to trigger releases of the transit-vehicle-overlay and park-and-ride-overlay that were not updated by #848.

More OTP-UI new map releases

---

packages/itinerary-body/src/util.ts

The `itinerary-body` component in writing the the following message to the console for each walk leg in an itinerary, each time the component renders:
This happens because the `getPlaceName` util in `itinerary-body` makes a call to `getCompanyForNetwork` to get a validated company name.  The latter function logs a warning when its `networkString` parameter is not in the otp-ui company config. This works fine for micromobility legs, but `getPlaceName` is also used for walk legs, which never have an associated network, so this warning emitted a lot and obscures other output in the console.  
This PR alters the call to `getCompanyFromNetwork` to only be made when the `place` parameter has a truthy network value to eliminates the invalid warnings
* Load the …

Eliminate erroneous warn logs in itinerary-body

---

packages/trip-details/src/components/fares.tsx

Always shows fare table, even if there is no default fare type defined

fix: show fares table even if no default fare defined

---

packages/printable-itinerary/src/__snapshots__/PrintableItinerary.story.tsx.snap
packages/printable-itinerary/src/accessibility-annotation.tsx
packages/printable-itinerary/src/index.tsx
packages/printable-itinerary/src/styled.ts

Seems like an oversight where we just forgot to pass the custom annotations.
| Before | After |
|--------|-------|
|<img width="693" height="667" alt="image" src="https://github.com/user-attachments/assets/8e2b2118-40c4-4e73-a247-816378a61f1f" />|<img width="693" height="667" alt="image" src="https://github.com/user-attachments/assets/7b9a3019-1f90-4701-b439-dc3ef201c125" />|
Before
After

Apply gradation map to accessibility annotations
